from django.urls import path
from .views import AttestationList, AttestationCreate, AttestationUpdate, AuditList, AuditCreate, AuditUpdate, \
    BooleanList, BooleanCreate, BooleanUpdate, ClusterList, ClusterCreate, ClusterUpdate, CountList, CountCreate, CountUpdate, \
    DataModelList, DataModelCreate, DataModelUpdate, FileList, FileCreate, FileUpdate, FloatList, FloatCreate, FloatUpdate, \
    IntervalList, IntervalCreate, IntervalUpdate, LinkList, LinkCreate, LinkUpdate, \
    OrdinalList, OrdinalCreate, OrdinalUpdate, ParticipationList, ParticipationCreate, ParticipationUpdate, PartyList, PartyCreate, PartyUpdate, \
    PredicateList, PredicateCreate, PredicateUpdate, QuantityList, QuantityCreate, QuantityUpdate, RDFObjectList, RDFObjectCreate, RDFObjectUpdate, \
    ReferenceRangeList, ReferenceRangeCreate, ReferenceRangeUpdate, SimpleReferenceRangeList, SimpleReferenceRangeCreate, SimpleReferenceRangeUpdate, \
    StringList, StringCreate, StringUpdate, TemporalList, TemporalCreate, TemporalUpdate, UnitsList, UnitsCreate, UnitsUpdate
    

urlpatterns = [
    path('attestation/', AttestationList.as_view(), name='attestation_list'),
    path('attestation/create/', AttestationCreate.as_view(), name='attestation_create'),
    path('attestation/update/<int:pk>/', AttestationUpdate.as_view(), name='attestation_update'),
    path('audit/', AuditList.as_view(), name='audit_list'),
    path('audit/create/', AuditCreate.as_view(), name='audit_create'),
    path('audit/update/<int:pk>/', AuditUpdate.as_view(), name='audit_update'),
    path('boolean/', BooleanList.as_view(), name='boolean_list'),
    path('boolean/create/', BooleanCreate.as_view(), name='boolean_create'),
    path('boolean/update/<int:pk>/', BooleanUpdate.as_view(), name='boolean_update'),
    path('cluster/', ClusterList.as_view(), name='cluster_list'),
    path('cluster/create/', ClusterCreate.as_view(), name='cluster_create'),
    path('cluster/update/<int:pk>/', ClusterUpdate.as_view(), name='cluster_update'),
    path('count/', CountList.as_view(), name='count_list'),
    path('count/create/', CountCreate.as_view(), name='count_create'),
    path('count/update/<int:pk>/', CountUpdate.as_view(), name='count_update'),
    path('datamodel/', DataModelList.as_view(), name='datamodel_list'),
    path('datamodel/create/', DataModelCreate.as_view(), name='datamodel_create'),
    path('datamodel/update/<int:pk>/', DataModelUpdate.as_view(), name='datamodel_update'),
    path('file/', FileList.as_view(), name='file_list'),
    path('file/create/', FileCreate.as_view(), name='file_create'),
    path('file/update/<int:pk>/', FileUpdate.as_view(), name='file_update'),
    path('float/', FloatList.as_view(), name='float_list'),
    path('float/create/', FloatCreate.as_view(), name='float_create'),
    path('float/update/<int:pk>/', FloatUpdate.as_view(), name='float_update'),
    path('interval/', IntervalList.as_view(), name='interval_list'),
    path('interval/create/', IntervalCreate.as_view(), name='interval_create'),
    path('interval/update/<int:pk>/', IntervalUpdate.as_view(), name='interval_update'),
    path('link/', LinkList.as_view(), name='link_list'),
    path('link/create/', LinkCreate.as_view(), name='link_create'),
    path('link/update/<int:pk>/', LinkUpdate.as_view(), name='link_update'),
    path('ordinal/', OrdinalList.as_view(), name='ordinal_list'),
    path('ordinal/create/', OrdinalCreate.as_view(), name='ordinal_create'),
    path('ordinal/update/<int:pk>/', OrdinalUpdate.as_view(), name='ordinal_update'),
    path('participation/', ParticipationList.as_view(), name='participation_list'),
    path('participation/create/', ParticipationCreate.as_view(), name='participation_create'),
    path('participation/update/<int:pk>/', ParticipationUpdate.as_view(), name='participation_update'),
    path('party/', PartyList.as_view(), name='party_list'),
    path('party/create/', PartyCreate.as_view(), name='party_create'),
    path('party/update/<int:pk>/', PartyUpdate.as_view(), name='party_update'),
    path('predicate/', PredicateList.as_view(), name='predicate_list'),
    path('predicate/create/', PredicateCreate.as_view(), name='predicate_create'),
    path('predicate/update/<int:pk>/', PredicateUpdate.as_view(), name='predicate_update'),
    path('quantity/', QuantityList.as_view(), name='quantity_list'),
    path('quantity/create/', QuantityCreate.as_view(), name='quantity_create'),
    path('quantity/update/<int:pk>/', QuantityUpdate.as_view(), name='quantity_update'),
    path('rdfobject/', RDFObjectList.as_view(), name='rdfobject_list'),
    path('rdfobject/create/', RDFObjectCreate.as_view(), name='rdfobject_create'),
    path('rdfobject/update/<int:pk>/', RDFObjectUpdate.as_view(), name='rdfobject_update'),
    path('referencerange/', ReferenceRangeList.as_view(), name='referencerange_list'),
    path('referencerange/create/', ReferenceRangeCreate.as_view(), name='referencerange_create'),
    path('referencerange/update/<int:pk>/', ReferenceRangeUpdate.as_view(), name='referencerange_update'),
    path('simplereferencerange/', SimpleReferenceRangeList.as_view(), name='simplereferencerange_list'),
    path('simplereferencerange/create/', SimpleReferenceRangeCreate.as_view(), name='simplereferencerange_create'),
    path('simplereferencerange/update/<int:pk>/', SimpleReferenceRangeUpdate.as_view(), name='simplereferencerange_update'),
    path('string/', StringList.as_view(), name='string_list'),
    path('string/create/', StringCreate.as_view(), name='string_create'),
    path('string/update/<int:pk>/', StringUpdate.as_view(), name='string_update'),
    path('temporal/', TemporalList.as_view(), name='temporal_list'),
    path('temporal/create/', TemporalCreate.as_view(), name='temporal_create'),
    path('temporal/update/<int:pk>/', TemporalUpdate.as_view(), name='temporal_update'),
    path('units/', UnitsList.as_view(), name='units_list'),
    path('units/create/', UnitsCreate.as_view(), name='units_create'),
    path('units/update/<int:pk>/', UnitsUpdate.as_view(), name='units_update'),
    ]

