# Generated by Django 4.1.7 on 2023-03-08 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dm',
            options={'ordering': ['project', 'title'], 'verbose_name': 'DataModel'},
        ),
    ]
