# Generated by Django 4.1.7 on 2023-03-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0002_alter_dm_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='predicate',
            name='ns_uri',
            field=models.CharField(default='', help_text='Enter the namespace URI for the abbreviation.', max_length=2000, verbose_name='Namespace URI'),
        ),
        migrations.AlterField(
            model_name='predicate',
            name='class_name',
            field=models.CharField(help_text='Enter a valid classname from the vocabulary.', max_length=50, verbose_name='Classname'),
        ),
        migrations.AlterField(
            model_name='predicate',
            name='ns_abbrev',
            field=models.CharField(help_text='Enter a namespace abbreviation.', max_length=30, verbose_name='Namespace Abbreviation'),
        ),
        migrations.DeleteModel(
            name='NS',
        ),
    ]
