# Generated by Django 4.1.7 on 2023-03-19 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0003_predicate_ns_uri_alter_predicate_class_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ns_abbrev', models.CharField(help_text='Enter a namespace abbreviation.', max_length=30, unique=True, verbose_name='Namespace Abbreviation')),
                ('ns_uri', models.CharField(default='', help_text='Enter the namespace URI for the abbreviation.', max_length=2000, unique=True, verbose_name='Namespace URI')),
            ],
            options={
                'verbose_name': 'Namespace',
                'verbose_name_plural': 'Namespaces',
                'ordering': ['ns_abbrev'],
            },
        ),
        migrations.CreateModel(
            name='SemanticLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_name', models.CharField(default='', help_text='Enter a human readable name for this Semantic Link. This is only used to aide selection, it is not part of the MC semantics.', max_length=100, verbose_name='Name')),
                ('class_name', models.CharField(default='', help_text='Enter a valid classname from the vocabulary.', max_length=50, verbose_name='Classname')),
                ('namespace', models.ForeignKey(blank=True, help_text='Select a namespace to define the RDF triple.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='component.namespace', verbose_name='Namespace')),
            ],
            options={
                'verbose_name': 'Semantic Link',
                'verbose_name_plural': 'Semantic Links',
                'ordering': ['sl_name'],
            },
        ),
        migrations.RemoveField(
            model_name='predobj',
            name='predicate',
        ),
        migrations.RemoveField(
            model_name='predobj',
            name='project',
        ),
        migrations.RemoveField(
            model_name='attestation',
            name='pred_obj',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='pred_obj',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='pred_obj',
        ),
        migrations.RemoveField(
            model_name='dm',
            name='pred_obj',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='pred_obj',
        ),
        migrations.RemoveField(
            model_name='party',
            name='pred_obj',
        ),
        migrations.RemoveField(
            model_name='referencerange',
            name='pred_obj',
        ),
        migrations.RemoveField(
            model_name='simplereferencerange',
            name='pred_obj',
        ),
        migrations.RemoveField(
            model_name='units',
            name='pred_obj',
        ),
        migrations.RemoveField(
            model_name='xdboolean',
            name='pred_obj',
        ),
        migrations.RemoveField(
            model_name='xdcount',
            name='pred_obj',
        ),
        migrations.RemoveField(
            model_name='xdfile',
            name='pred_obj',
        ),
        migrations.RemoveField(
            model_name='xdfloat',
            name='pred_obj',
        ),
        migrations.RemoveField(
            model_name='xdinterval',
            name='pred_obj',
        ),
        migrations.RemoveField(
            model_name='xdlink',
            name='pred_obj',
        ),
        migrations.RemoveField(
            model_name='xdordinal',
            name='pred_obj',
        ),
        migrations.RemoveField(
            model_name='xdquantity',
            name='pred_obj',
        ),
        migrations.RemoveField(
            model_name='xdstring',
            name='pred_obj',
        ),
        migrations.RemoveField(
            model_name='xdtemporal',
            name='pred_obj',
        ),
        migrations.DeleteModel(
            name='Predicate',
        ),
        migrations.DeleteModel(
            name='PredObj',
        ),
        migrations.AddField(
            model_name='attestation',
            name='sem_links',
            field=models.ManyToManyField(blank=True, help_text='Select or create a new set of semantic links to define this item.', to='component.semanticlink', verbose_name='Semantic Links'),
        ),
        migrations.AddField(
            model_name='audit',
            name='sem_links',
            field=models.ManyToManyField(blank=True, help_text='Select or create a new set of semantic links to define this item.', to='component.semanticlink', verbose_name='Semantic Links'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='sem_links',
            field=models.ManyToManyField(blank=True, help_text='Select or create a new set of semantic links to define this item.', to='component.semanticlink', verbose_name='Semantic Links'),
        ),
        migrations.AddField(
            model_name='dm',
            name='sem_links',
            field=models.ManyToManyField(blank=True, help_text='Select or create a new set of semantic links.', to='component.semanticlink', verbose_name='Semantic Links'),
        ),
        migrations.AddField(
            model_name='participation',
            name='sem_links',
            field=models.ManyToManyField(blank=True, help_text='Select or create a new set of semantic links to define this item.', to='component.semanticlink', verbose_name='Semantic Links'),
        ),
        migrations.AddField(
            model_name='party',
            name='sem_links',
            field=models.ManyToManyField(blank=True, help_text='Select or create a new set of semantic links to define this item.', to='component.semanticlink', verbose_name='Semantic Links'),
        ),
        migrations.AddField(
            model_name='referencerange',
            name='sem_links',
            field=models.ManyToManyField(blank=True, help_text='Select or create a new set of semantic links to define this item.', to='component.semanticlink', verbose_name='Semantic Links'),
        ),
        migrations.AddField(
            model_name='simplereferencerange',
            name='sem_links',
            field=models.ManyToManyField(blank=True, help_text='Select or create a new set of semantic links to define this item.', to='component.semanticlink', verbose_name='Semantic Links'),
        ),
        migrations.AddField(
            model_name='units',
            name='sem_links',
            field=models.ManyToManyField(blank=True, help_text='Select or create a new set of semantic links to define this item.', to='component.semanticlink', verbose_name='Semantic Links'),
        ),
        migrations.AddField(
            model_name='xdboolean',
            name='sem_links',
            field=models.ManyToManyField(blank=True, help_text='Select or create a new set of semantic links to define this item.', to='component.semanticlink', verbose_name='Semantic Links'),
        ),
        migrations.AddField(
            model_name='xdcount',
            name='sem_links',
            field=models.ManyToManyField(blank=True, help_text='Select or create a new set of semantic links to define this item.', to='component.semanticlink', verbose_name='Semantic Links'),
        ),
        migrations.AddField(
            model_name='xdfile',
            name='sem_links',
            field=models.ManyToManyField(blank=True, help_text='Select or create a new set of semantic links to define this item.', to='component.semanticlink', verbose_name='Semantic Links'),
        ),
        migrations.AddField(
            model_name='xdfloat',
            name='sem_links',
            field=models.ManyToManyField(blank=True, help_text='Select or create a new set of semantic links to define this item.', to='component.semanticlink', verbose_name='Semantic Links'),
        ),
        migrations.AddField(
            model_name='xdinterval',
            name='sem_links',
            field=models.ManyToManyField(blank=True, help_text='Select or create a new set of semantic links to define this item.', to='component.semanticlink', verbose_name='Semantic Links'),
        ),
        migrations.AddField(
            model_name='xdlink',
            name='sem_links',
            field=models.ManyToManyField(blank=True, help_text='Select or create a new set of semantic links to define this item.', to='component.semanticlink', verbose_name='Semantic Links'),
        ),
        migrations.AddField(
            model_name='xdordinal',
            name='sem_links',
            field=models.ManyToManyField(blank=True, help_text='Select or create a new set of semantic links to define this item.', to='component.semanticlink', verbose_name='Semantic Links'),
        ),
        migrations.AddField(
            model_name='xdquantity',
            name='sem_links',
            field=models.ManyToManyField(blank=True, help_text='Select or create a new set of semantic links to define this item.', to='component.semanticlink', verbose_name='Semantic Links'),
        ),
        migrations.AddField(
            model_name='xdstring',
            name='sem_links',
            field=models.ManyToManyField(blank=True, help_text='Select or create a new set of semantic links to define this item.', to='component.semanticlink', verbose_name='Semantic Links'),
        ),
        migrations.AddField(
            model_name='xdtemporal',
            name='sem_links',
            field=models.ManyToManyField(blank=True, help_text='Select or create a new set of semantic links to define this item.', to='component.semanticlink', verbose_name='Semantic Links'),
        ),
    ]
