# Generated by Django 4.0.1 on 2022-01-20 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datamodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=50, verbose_name='Project')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('copyright', models.CharField(max_length=250, verbose_name='Copyright')),
                ('author', models.CharField(max_length=250, verbose_name='Author')),
                ('definition_url', models.CharField(max_length=500, verbose_name='Defining URL')),
                ('namespaces', models.TextField(verbose_name='Additional Namespaces')),
                ('dmid', models.CharField(max_length=40, verbose_name='Data Model ID')),
                ('dataid', models.CharField(max_length=40, verbose_name='Data Cluster ID')),
                ('schema', models.TextField(verbose_name='XML Schema')),
                ('rdf', models.TextField(verbose_name='RDF')),
            ],
        ),
        migrations.CreateModel(
            name='JSONstore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbtype', models.CharField(max_length=25, verbose_name='Storage Type')),
                ('name', models.CharField(max_length=250, verbose_name='Storage Name')),
                ('host', models.CharField(max_length=500, verbose_name='Host Name')),
                ('port', models.CharField(max_length=10, verbose_name='Port Number')),
                ('dbname', models.CharField(max_length=250, verbose_name='Database Name')),
                ('user', models.CharField(max_length=250, verbose_name='User Name')),
                ('pw', models.CharField(max_length=250, verbose_name='User Password')),
                ('hostip', models.CharField(max_length=45, verbose_name='Host IP')),
                ('forests', models.PositiveSmallIntegerField(verbose_name='Forests')),
                ('asport', models.CharField(max_length=10, verbose_name='App Server Port Number')),
            ],
        ),
        migrations.CreateModel(
            name='RDFstore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbtype', models.CharField(max_length=25, verbose_name='Storage Type')),
                ('name', models.CharField(max_length=250, verbose_name='Storage Name')),
                ('host', models.CharField(max_length=500, verbose_name='Host Name')),
                ('port', models.CharField(max_length=10, verbose_name='Port Number')),
                ('dbname', models.CharField(max_length=250, verbose_name='Database Name')),
                ('user', models.CharField(max_length=250, verbose_name='User Name')),
                ('pw', models.CharField(max_length=250, verbose_name='User Password')),
                ('hostip', models.CharField(max_length=45, verbose_name='Host IP')),
                ('forests', models.PositiveSmallIntegerField(verbose_name='Forests')),
                ('asport', models.CharField(max_length=10, verbose_name='App Server Port Number')),
            ],
        ),
        migrations.CreateModel(
            name='XMLstore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbtype', models.CharField(max_length=40, verbose_name='Storage Type')),
                ('name', models.CharField(max_length=250, verbose_name='Storage Name')),
                ('host', models.CharField(max_length=500, verbose_name='Host Name')),
                ('port', models.CharField(max_length=10, verbose_name='Port Number')),
                ('dbname', models.CharField(max_length=250, verbose_name='Database Name')),
                ('user', models.CharField(max_length=250, verbose_name='User Name')),
                ('pw', models.CharField(max_length=250, verbose_name='User Password')),
                ('hostip', models.CharField(max_length=45, verbose_name='Host IP')),
                ('forests', models.PositiveSmallIntegerField(verbose_name='Forests')),
                ('asport', models.CharField(max_length=10, verbose_name='App Server Port Number')),
            ],
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Time Stamp')),
                ('log', models.TextField(verbose_name='CSV Log')),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csvmodeler.datamodel')),
            ],
        ),
        migrations.AddField(
            model_name='datamodel',
            name='json_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csvmodeler.jsonstore'),
        ),
        migrations.AddField(
            model_name='datamodel',
            name='rdf_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csvmodeler.rdfstore'),
        ),
        migrations.AddField(
            model_name='datamodel',
            name='xml_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csvmodeler.xmlstore'),
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='CSV Column Header')),
                ('label', models.CharField(max_length=250, verbose_name='Label Value')),
                ('datatype', models.CharField(max_length=10, verbose_name='Datatype')),
                ('min_len', models.PositiveSmallIntegerField(verbose_name='Minimum Length')),
                ('max_len', models.PositiveSmallIntegerField(verbose_name='Maximum Length')),
                ('choices', models.TextField(verbose_name='String Enumerations')),
                ('regex', models.CharField(max_length=100, verbose_name='Regular Expression')),
                ('min_incl', models.CharField(max_length=100, verbose_name='Minimum Value (Inclusive)')),
                ('max_incl', models.CharField(max_length=100, verbose_name='Maximum Value (Inclusive)')),
                ('min_excl', models.CharField(max_length=100, verbose_name='Minimum Value (Exclusive)')),
                ('max_excl', models.CharField(max_length=100, verbose_name='Maximum Value (Exclusive)')),
                ('description', models.TextField(verbose_name='Description')),
                ('definition_url', models.CharField(max_length=500, verbose_name='Defining URL')),
                ('pred_obj', models.TextField(verbose_name='List of predicate/object pairs')),
                ('def_text', models.CharField(max_length=500, verbose_name='Default Text')),
                ('def_num', models.CharField(max_length=100, verbose_name='Default Number')),
                ('units', models.CharField(max_length=50, verbose_name='Units')),
                ('mcid', models.CharField(max_length=40, verbose_name='Component ID')),
                ('adid', models.CharField(max_length=40, verbose_name='Adapter ID')),
                ('model_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csvmodeler.datamodel')),
            ],
        ),
    ]
