# Generated by Django 2.0.3 on 2018-04-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmgen', '0018_auto_20180410_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='xdstring',
            name='str_fmt',
            field=models.CharField(blank=True, help_text='Enter a regular expression used to constrain the string to a specific format. See the XML reduced regex set here: https://www.regular-expressions.info/xml.html ', max_length=60, verbose_name='String Format'),
        ),
        migrations.AlterField(
            model_name='attestation',
            name='ct_id',
            field=models.CharField(default='cjfwlz1ip00007ol3vzn6o2bf', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='ct_id',
            field=models.CharField(default='cjfwlz1ip00007ol3vzn6o2bf', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='ct_id',
            field=models.CharField(default='cjfwlz1ip00007ol3vzn6o2bf', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='dm',
            name='ct_id',
            field=models.CharField(default='cjfwlz1k300027ol35q42wdwh', editable=False, help_text='The unique identifier for the DM.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='ct_id',
            field=models.CharField(default='cjfwlz1ip00007ol3vzn6o2bf', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='party',
            name='ct_id',
            field=models.CharField(default='cjfwlz1ip00007ol3vzn6o2bf', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='referencerange',
            name='adapter_ctid',
            field=models.CharField(default='cjfwlz1iq00017ol3u4z231t7', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='referencerange',
            name='ct_id',
            field=models.CharField(default='cjfwlz1ip00007ol3vzn6o2bf', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='simplereferencerange',
            name='adapter_ctid',
            field=models.CharField(default='cjfwlz1iq00017ol3u4z231t7', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='simplereferencerange',
            name='ct_id',
            field=models.CharField(default='cjfwlz1ip00007ol3vzn6o2bf', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='units',
            name='adapter_ctid',
            field=models.CharField(default='cjfwlz1iq00017ol3u4z231t7', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='units',
            name='ct_id',
            field=models.CharField(default='cjfwlz1ip00007ol3vzn6o2bf', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdboolean',
            name='adapter_ctid',
            field=models.CharField(default='cjfwlz1iq00017ol3u4z231t7', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdboolean',
            name='ct_id',
            field=models.CharField(default='cjfwlz1ip00007ol3vzn6o2bf', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdcount',
            name='adapter_ctid',
            field=models.CharField(default='cjfwlz1iq00017ol3u4z231t7', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdcount',
            name='ct_id',
            field=models.CharField(default='cjfwlz1ip00007ol3vzn6o2bf', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdfile',
            name='adapter_ctid',
            field=models.CharField(default='cjfwlz1iq00017ol3u4z231t7', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdfile',
            name='ct_id',
            field=models.CharField(default='cjfwlz1ip00007ol3vzn6o2bf', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdfloat',
            name='adapter_ctid',
            field=models.CharField(default='cjfwlz1iq00017ol3u4z231t7', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdfloat',
            name='ct_id',
            field=models.CharField(default='cjfwlz1ip00007ol3vzn6o2bf', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdinterval',
            name='adapter_ctid',
            field=models.CharField(default='cjfwlz1iq00017ol3u4z231t7', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdinterval',
            name='ct_id',
            field=models.CharField(default='cjfwlz1ip00007ol3vzn6o2bf', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdlink',
            name='adapter_ctid',
            field=models.CharField(default='cjfwlz1iq00017ol3u4z231t7', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdlink',
            name='ct_id',
            field=models.CharField(default='cjfwlz1ip00007ol3vzn6o2bf', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdordinal',
            name='adapter_ctid',
            field=models.CharField(default='cjfwlz1iq00017ol3u4z231t7', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdordinal',
            name='ct_id',
            field=models.CharField(default='cjfwlz1ip00007ol3vzn6o2bf', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdquantity',
            name='adapter_ctid',
            field=models.CharField(default='cjfwlz1iq00017ol3u4z231t7', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdquantity',
            name='ct_id',
            field=models.CharField(default='cjfwlz1ip00007ol3vzn6o2bf', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdratio',
            name='adapter_ctid',
            field=models.CharField(default='cjfwlz1iq00017ol3u4z231t7', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdratio',
            name='ct_id',
            field=models.CharField(default='cjfwlz1ip00007ol3vzn6o2bf', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdstring',
            name='adapter_ctid',
            field=models.CharField(default='cjfwlz1iq00017ol3u4z231t7', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdstring',
            name='ct_id',
            field=models.CharField(default='cjfwlz1ip00007ol3vzn6o2bf', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdtemporal',
            name='adapter_ctid',
            field=models.CharField(default='cjfwlz1iq00017ol3u4z231t7', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdtemporal',
            name='ct_id',
            field=models.CharField(default='cjfwlz1ip00007ol3vzn6o2bf', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
    ]
