# Generated by Django 2.0.3 on 2018-04-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmgen', '0022_auto_20180422_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencerange',
            name='allow_location',
            field=models.BooleanField(default=False, help_text='Check this box to allow a decimal longitude and latitude location.', verbose_name='Allow Location?'),
        ),
        migrations.AddField(
            model_name='referencerange',
            name='allow_mod',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time for last modified element.', verbose_name='Allow Time Modified?'),
        ),
        migrations.AddField(
            model_name='referencerange',
            name='allow_tr',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time Recorded element.', verbose_name='Allow Time Recorded?'),
        ),
        migrations.AddField(
            model_name='referencerange',
            name='allow_vtb',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time Begin element.', verbose_name='Allow Valid Time Begin?'),
        ),
        migrations.AddField(
            model_name='referencerange',
            name='allow_vte',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time End element.', verbose_name='Allow Valid Time End?'),
        ),
        migrations.AddField(
            model_name='simplereferencerange',
            name='allow_location',
            field=models.BooleanField(default=False, help_text='Check this box to allow a decimal longitude and latitude location.', verbose_name='Allow Location?'),
        ),
        migrations.AddField(
            model_name='simplereferencerange',
            name='allow_mod',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time for last modified element.', verbose_name='Allow Time Modified?'),
        ),
        migrations.AddField(
            model_name='simplereferencerange',
            name='allow_tr',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time Recorded element.', verbose_name='Allow Time Recorded?'),
        ),
        migrations.AddField(
            model_name='simplereferencerange',
            name='allow_vtb',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time Begin element.', verbose_name='Allow Valid Time Begin?'),
        ),
        migrations.AddField(
            model_name='simplereferencerange',
            name='allow_vte',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time End element.', verbose_name='Allow Valid Time End?'),
        ),
        migrations.AddField(
            model_name='units',
            name='allow_location',
            field=models.BooleanField(default=False, help_text='Check this box to allow a decimal longitude and latitude location.', verbose_name='Allow Location?'),
        ),
        migrations.AddField(
            model_name='units',
            name='allow_mod',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time for last modified element.', verbose_name='Allow Time Modified?'),
        ),
        migrations.AddField(
            model_name='units',
            name='allow_tr',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time Recorded element.', verbose_name='Allow Time Recorded?'),
        ),
        migrations.AddField(
            model_name='units',
            name='allow_vtb',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time Begin element.', verbose_name='Allow Valid Time Begin?'),
        ),
        migrations.AddField(
            model_name='units',
            name='allow_vte',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time End element.', verbose_name='Allow Valid Time End?'),
        ),
        migrations.AddField(
            model_name='xdboolean',
            name='allow_location',
            field=models.BooleanField(default=False, help_text='Check this box to allow a decimal longitude and latitude location.', verbose_name='Allow Location?'),
        ),
        migrations.AddField(
            model_name='xdboolean',
            name='allow_mod',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time for last modified element.', verbose_name='Allow Time Modified?'),
        ),
        migrations.AddField(
            model_name='xdboolean',
            name='allow_tr',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time Recorded element.', verbose_name='Allow Time Recorded?'),
        ),
        migrations.AddField(
            model_name='xdboolean',
            name='allow_vtb',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time Begin element.', verbose_name='Allow Valid Time Begin?'),
        ),
        migrations.AddField(
            model_name='xdboolean',
            name='allow_vte',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time End element.', verbose_name='Allow Valid Time End?'),
        ),
        migrations.AddField(
            model_name='xdcount',
            name='allow_location',
            field=models.BooleanField(default=False, help_text='Check this box to allow a decimal longitude and latitude location.', verbose_name='Allow Location?'),
        ),
        migrations.AddField(
            model_name='xdcount',
            name='allow_mod',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time for last modified element.', verbose_name='Allow Time Modified?'),
        ),
        migrations.AddField(
            model_name='xdcount',
            name='allow_tr',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time Recorded element.', verbose_name='Allow Time Recorded?'),
        ),
        migrations.AddField(
            model_name='xdcount',
            name='allow_vtb',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time Begin element.', verbose_name='Allow Valid Time Begin?'),
        ),
        migrations.AddField(
            model_name='xdcount',
            name='allow_vte',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time End element.', verbose_name='Allow Valid Time End?'),
        ),
        migrations.AddField(
            model_name='xdfile',
            name='allow_location',
            field=models.BooleanField(default=False, help_text='Check this box to allow a decimal longitude and latitude location.', verbose_name='Allow Location?'),
        ),
        migrations.AddField(
            model_name='xdfile',
            name='allow_mod',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time for last modified element.', verbose_name='Allow Time Modified?'),
        ),
        migrations.AddField(
            model_name='xdfile',
            name='allow_tr',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time Recorded element.', verbose_name='Allow Time Recorded?'),
        ),
        migrations.AddField(
            model_name='xdfile',
            name='allow_vtb',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time Begin element.', verbose_name='Allow Valid Time Begin?'),
        ),
        migrations.AddField(
            model_name='xdfile',
            name='allow_vte',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time End element.', verbose_name='Allow Valid Time End?'),
        ),
        migrations.AddField(
            model_name='xdfloat',
            name='allow_location',
            field=models.BooleanField(default=False, help_text='Check this box to allow a decimal longitude and latitude location.', verbose_name='Allow Location?'),
        ),
        migrations.AddField(
            model_name='xdfloat',
            name='allow_mod',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time for last modified element.', verbose_name='Allow Time Modified?'),
        ),
        migrations.AddField(
            model_name='xdfloat',
            name='allow_tr',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time Recorded element.', verbose_name='Allow Time Recorded?'),
        ),
        migrations.AddField(
            model_name='xdfloat',
            name='allow_vtb',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time Begin element.', verbose_name='Allow Valid Time Begin?'),
        ),
        migrations.AddField(
            model_name='xdfloat',
            name='allow_vte',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time End element.', verbose_name='Allow Valid Time End?'),
        ),
        migrations.AddField(
            model_name='xdinterval',
            name='allow_location',
            field=models.BooleanField(default=False, help_text='Check this box to allow a decimal longitude and latitude location.', verbose_name='Allow Location?'),
        ),
        migrations.AddField(
            model_name='xdinterval',
            name='allow_mod',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time for last modified element.', verbose_name='Allow Time Modified?'),
        ),
        migrations.AddField(
            model_name='xdinterval',
            name='allow_tr',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time Recorded element.', verbose_name='Allow Time Recorded?'),
        ),
        migrations.AddField(
            model_name='xdinterval',
            name='allow_vtb',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time Begin element.', verbose_name='Allow Valid Time Begin?'),
        ),
        migrations.AddField(
            model_name='xdinterval',
            name='allow_vte',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time End element.', verbose_name='Allow Valid Time End?'),
        ),
        migrations.AddField(
            model_name='xdlink',
            name='allow_location',
            field=models.BooleanField(default=False, help_text='Check this box to allow a decimal longitude and latitude location.', verbose_name='Allow Location?'),
        ),
        migrations.AddField(
            model_name='xdlink',
            name='allow_mod',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time for last modified element.', verbose_name='Allow Time Modified?'),
        ),
        migrations.AddField(
            model_name='xdlink',
            name='allow_tr',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time Recorded element.', verbose_name='Allow Time Recorded?'),
        ),
        migrations.AddField(
            model_name='xdlink',
            name='allow_vtb',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time Begin element.', verbose_name='Allow Valid Time Begin?'),
        ),
        migrations.AddField(
            model_name='xdlink',
            name='allow_vte',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time End element.', verbose_name='Allow Valid Time End?'),
        ),
        migrations.AddField(
            model_name='xdordinal',
            name='allow_location',
            field=models.BooleanField(default=False, help_text='Check this box to allow a decimal longitude and latitude location.', verbose_name='Allow Location?'),
        ),
        migrations.AddField(
            model_name='xdordinal',
            name='allow_mod',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time for last modified element.', verbose_name='Allow Time Modified?'),
        ),
        migrations.AddField(
            model_name='xdordinal',
            name='allow_tr',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time Recorded element.', verbose_name='Allow Time Recorded?'),
        ),
        migrations.AddField(
            model_name='xdordinal',
            name='allow_vtb',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time Begin element.', verbose_name='Allow Valid Time Begin?'),
        ),
        migrations.AddField(
            model_name='xdordinal',
            name='allow_vte',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time End element.', verbose_name='Allow Valid Time End?'),
        ),
        migrations.AddField(
            model_name='xdquantity',
            name='allow_location',
            field=models.BooleanField(default=False, help_text='Check this box to allow a decimal longitude and latitude location.', verbose_name='Allow Location?'),
        ),
        migrations.AddField(
            model_name='xdquantity',
            name='allow_mod',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time for last modified element.', verbose_name='Allow Time Modified?'),
        ),
        migrations.AddField(
            model_name='xdquantity',
            name='allow_tr',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time Recorded element.', verbose_name='Allow Time Recorded?'),
        ),
        migrations.AddField(
            model_name='xdquantity',
            name='allow_vtb',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time Begin element.', verbose_name='Allow Valid Time Begin?'),
        ),
        migrations.AddField(
            model_name='xdquantity',
            name='allow_vte',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time End element.', verbose_name='Allow Valid Time End?'),
        ),
        migrations.AddField(
            model_name='xdratio',
            name='allow_location',
            field=models.BooleanField(default=False, help_text='Check this box to allow a decimal longitude and latitude location.', verbose_name='Allow Location?'),
        ),
        migrations.AddField(
            model_name='xdratio',
            name='allow_mod',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time for last modified element.', verbose_name='Allow Time Modified?'),
        ),
        migrations.AddField(
            model_name='xdratio',
            name='allow_tr',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time Recorded element.', verbose_name='Allow Time Recorded?'),
        ),
        migrations.AddField(
            model_name='xdratio',
            name='allow_vtb',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time Begin element.', verbose_name='Allow Valid Time Begin?'),
        ),
        migrations.AddField(
            model_name='xdratio',
            name='allow_vte',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time End element.', verbose_name='Allow Valid Time End?'),
        ),
        migrations.AddField(
            model_name='xdstring',
            name='allow_location',
            field=models.BooleanField(default=False, help_text='Check this box to allow a decimal longitude and latitude location.', verbose_name='Allow Location?'),
        ),
        migrations.AddField(
            model_name='xdstring',
            name='allow_mod',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time for last modified element.', verbose_name='Allow Time Modified?'),
        ),
        migrations.AddField(
            model_name='xdstring',
            name='allow_tr',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time Recorded element.', verbose_name='Allow Time Recorded?'),
        ),
        migrations.AddField(
            model_name='xdstring',
            name='allow_vtb',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time Begin element.', verbose_name='Allow Valid Time Begin?'),
        ),
        migrations.AddField(
            model_name='xdstring',
            name='allow_vte',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time End element.', verbose_name='Allow Valid Time End?'),
        ),
        migrations.AddField(
            model_name='xdtemporal',
            name='allow_location',
            field=models.BooleanField(default=False, help_text='Check this box to allow a decimal longitude and latitude location.', verbose_name='Allow Location?'),
        ),
        migrations.AddField(
            model_name='xdtemporal',
            name='allow_mod',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time for last modified element.', verbose_name='Allow Time Modified?'),
        ),
        migrations.AddField(
            model_name='xdtemporal',
            name='allow_tr',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time Recorded element.', verbose_name='Allow Time Recorded?'),
        ),
        migrations.AddField(
            model_name='xdtemporal',
            name='allow_vtb',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time Begin element.', verbose_name='Allow Valid Time Begin?'),
        ),
        migrations.AddField(
            model_name='xdtemporal',
            name='allow_vte',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time End element.', verbose_name='Allow Valid Time End?'),
        ),
        migrations.AlterField(
            model_name='attestation',
            name='ct_id',
            field=models.CharField(default='cjgaoqway0000h9l32r6ahv6n', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='ct_id',
            field=models.CharField(default='cjgaoqway0000h9l32r6ahv6n', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='ct_id',
            field=models.CharField(default='cjgaoqway0000h9l32r6ahv6n', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='dm',
            name='ct_id',
            field=models.CharField(default='cjgaoqwcd0002h9l3f8ssulkc', editable=False, help_text='The unique identifier for the DM.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='ct_id',
            field=models.CharField(default='cjgaoqway0000h9l32r6ahv6n', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='party',
            name='ct_id',
            field=models.CharField(default='cjgaoqway0000h9l32r6ahv6n', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='referencerange',
            name='adapter_ctid',
            field=models.CharField(default='cjgaoqwaz0001h9l3fjivfcud', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='referencerange',
            name='ct_id',
            field=models.CharField(default='cjgaoqway0000h9l32r6ahv6n', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='simplereferencerange',
            name='adapter_ctid',
            field=models.CharField(default='cjgaoqwaz0001h9l3fjivfcud', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='simplereferencerange',
            name='ct_id',
            field=models.CharField(default='cjgaoqway0000h9l32r6ahv6n', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='units',
            name='adapter_ctid',
            field=models.CharField(default='cjgaoqwaz0001h9l3fjivfcud', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='units',
            name='ct_id',
            field=models.CharField(default='cjgaoqway0000h9l32r6ahv6n', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdboolean',
            name='adapter_ctid',
            field=models.CharField(default='cjgaoqwaz0001h9l3fjivfcud', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdboolean',
            name='ct_id',
            field=models.CharField(default='cjgaoqway0000h9l32r6ahv6n', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdcount',
            name='adapter_ctid',
            field=models.CharField(default='cjgaoqwaz0001h9l3fjivfcud', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdcount',
            name='ct_id',
            field=models.CharField(default='cjgaoqway0000h9l32r6ahv6n', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdfile',
            name='adapter_ctid',
            field=models.CharField(default='cjgaoqwaz0001h9l3fjivfcud', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdfile',
            name='ct_id',
            field=models.CharField(default='cjgaoqway0000h9l32r6ahv6n', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdfloat',
            name='adapter_ctid',
            field=models.CharField(default='cjgaoqwaz0001h9l3fjivfcud', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdfloat',
            name='ct_id',
            field=models.CharField(default='cjgaoqway0000h9l32r6ahv6n', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdinterval',
            name='adapter_ctid',
            field=models.CharField(default='cjgaoqwaz0001h9l3fjivfcud', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdinterval',
            name='ct_id',
            field=models.CharField(default='cjgaoqway0000h9l32r6ahv6n', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdlink',
            name='adapter_ctid',
            field=models.CharField(default='cjgaoqwaz0001h9l3fjivfcud', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdlink',
            name='ct_id',
            field=models.CharField(default='cjgaoqway0000h9l32r6ahv6n', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdordinal',
            name='adapter_ctid',
            field=models.CharField(default='cjgaoqwaz0001h9l3fjivfcud', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdordinal',
            name='ct_id',
            field=models.CharField(default='cjgaoqway0000h9l32r6ahv6n', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdquantity',
            name='adapter_ctid',
            field=models.CharField(default='cjgaoqwaz0001h9l3fjivfcud', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdquantity',
            name='ct_id',
            field=models.CharField(default='cjgaoqway0000h9l32r6ahv6n', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdratio',
            name='adapter_ctid',
            field=models.CharField(default='cjgaoqwaz0001h9l3fjivfcud', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdratio',
            name='ct_id',
            field=models.CharField(default='cjgaoqway0000h9l32r6ahv6n', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdstring',
            name='adapter_ctid',
            field=models.CharField(default='cjgaoqwaz0001h9l3fjivfcud', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdstring',
            name='ct_id',
            field=models.CharField(default='cjgaoqway0000h9l32r6ahv6n', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdtemporal',
            name='adapter_ctid',
            field=models.CharField(default='cjgaoqwaz0001h9l3fjivfcud', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdtemporal',
            name='ct_id',
            field=models.CharField(default='cjgaoqway0000h9l32r6ahv6n', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
    ]
