# Generated by Django 2.0.5 on 2018-06-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmgen', '0025_auto_20180422_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencerange',
            name='require_act',
            field=models.BooleanField(default=False, help_text='Check this box to require an Access Control Tag element.', verbose_name='Require Access Control Tag?'),
        ),
        migrations.AddField(
            model_name='simplereferencerange',
            name='require_act',
            field=models.BooleanField(default=False, help_text='Check this box to require an Access Control Tag element.', verbose_name='Require Access Control Tag?'),
        ),
        migrations.AddField(
            model_name='units',
            name='require_act',
            field=models.BooleanField(default=False, help_text='Check this box to require an Access Control Tag element.', verbose_name='Require Access Control Tag?'),
        ),
        migrations.AddField(
            model_name='xdboolean',
            name='require_act',
            field=models.BooleanField(default=False, help_text='Check this box to require an Access Control Tag element.', verbose_name='Require Access Control Tag?'),
        ),
        migrations.AddField(
            model_name='xdcount',
            name='require_act',
            field=models.BooleanField(default=False, help_text='Check this box to require an Access Control Tag element.', verbose_name='Require Access Control Tag?'),
        ),
        migrations.AddField(
            model_name='xdfile',
            name='require_act',
            field=models.BooleanField(default=False, help_text='Check this box to require an Access Control Tag element.', verbose_name='Require Access Control Tag?'),
        ),
        migrations.AddField(
            model_name='xdfloat',
            name='require_act',
            field=models.BooleanField(default=False, help_text='Check this box to require an Access Control Tag element.', verbose_name='Require Access Control Tag?'),
        ),
        migrations.AddField(
            model_name='xdinterval',
            name='require_act',
            field=models.BooleanField(default=False, help_text='Check this box to require an Access Control Tag element.', verbose_name='Require Access Control Tag?'),
        ),
        migrations.AddField(
            model_name='xdlink',
            name='require_act',
            field=models.BooleanField(default=False, help_text='Check this box to require an Access Control Tag element.', verbose_name='Require Access Control Tag?'),
        ),
        migrations.AddField(
            model_name='xdordinal',
            name='require_act',
            field=models.BooleanField(default=False, help_text='Check this box to require an Access Control Tag element.', verbose_name='Require Access Control Tag?'),
        ),
        migrations.AddField(
            model_name='xdquantity',
            name='require_act',
            field=models.BooleanField(default=False, help_text='Check this box to require an Access Control Tag element.', verbose_name='Require Access Control Tag?'),
        ),
        migrations.AddField(
            model_name='xdratio',
            name='require_act',
            field=models.BooleanField(default=False, help_text='Check this box to require an Access Control Tag element.', verbose_name='Require Access Control Tag?'),
        ),
        migrations.AddField(
            model_name='xdstring',
            name='require_act',
            field=models.BooleanField(default=False, help_text='Check this box to require an Access Control Tag element.', verbose_name='Require Access Control Tag?'),
        ),
        migrations.AddField(
            model_name='xdtemporal',
            name='require_act',
            field=models.BooleanField(default=False, help_text='Check this box to require an Access Control Tag element.', verbose_name='Require Access Control Tag?'),
        ),
        migrations.AlterField(
            model_name='attestation',
            name='ct_id',
            field=models.CharField(default='cjieyi2c80000k4l342jqwh9n', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='attestation',
            name='validate',
            field=models.BooleanField(default=False, help_text='Hard validation is when the UI enforces criteria on input fields. Soft validation allows users to input any value, warns them when it is not within parameters of the component. Then offers to allow correction or select an Exceptional Value as explaination.', verbose_name='Hard Validate?'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='ct_id',
            field=models.CharField(default='cjieyi2c80000k4l342jqwh9n', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='validate',
            field=models.BooleanField(default=False, help_text='Hard validation is when the UI enforces criteria on input fields. Soft validation allows users to input any value, warns them when it is not within parameters of the component. Then offers to allow correction or select an Exceptional Value as explaination.', verbose_name='Hard Validate?'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='ct_id',
            field=models.CharField(default='cjieyi2c80000k4l342jqwh9n', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='validate',
            field=models.BooleanField(default=False, help_text='Hard validation is when the UI enforces criteria on input fields. Soft validation allows users to input any value, warns them when it is not within parameters of the component. Then offers to allow correction or select an Exceptional Value as explaination.', verbose_name='Hard Validate?'),
        ),
        migrations.AlterField(
            model_name='dm',
            name='ct_id',
            field=models.CharField(default='cjieyi2e40002k4l3z9x78pza', editable=False, help_text='The unique identifier for the DM.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='ct_id',
            field=models.CharField(default='cjieyi2c80000k4l342jqwh9n', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='validate',
            field=models.BooleanField(default=False, help_text='Hard validation is when the UI enforces criteria on input fields. Soft validation allows users to input any value, warns them when it is not within parameters of the component. Then offers to allow correction or select an Exceptional Value as explaination.', verbose_name='Hard Validate?'),
        ),
        migrations.AlterField(
            model_name='party',
            name='ct_id',
            field=models.CharField(default='cjieyi2c80000k4l342jqwh9n', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='party',
            name='validate',
            field=models.BooleanField(default=False, help_text='Hard validation is when the UI enforces criteria on input fields. Soft validation allows users to input any value, warns them when it is not within parameters of the component. Then offers to allow correction or select an Exceptional Value as explaination.', verbose_name='Hard Validate?'),
        ),
        migrations.AlterField(
            model_name='referencerange',
            name='adapter_ctid',
            field=models.CharField(default='cjieyi2cb0001k4l3axg0o0f4', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='referencerange',
            name='allow_location',
            field=models.BooleanField(default=False, help_text='Check this box to allow a decimal longitude and latitude location even when not required.', verbose_name='Allow Location?'),
        ),
        migrations.AlterField(
            model_name='referencerange',
            name='allow_mod',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time for last modified element even when not required.', verbose_name='Allow Time Modified?'),
        ),
        migrations.AlterField(
            model_name='referencerange',
            name='allow_tr',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time Recorded element even when not required.', verbose_name='Allow Time Recorded?'),
        ),
        migrations.AlterField(
            model_name='referencerange',
            name='allow_vtb',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time Begin element even when not required.', verbose_name='Allow Valid Time Begin?'),
        ),
        migrations.AlterField(
            model_name='referencerange',
            name='allow_vte',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time End element even when not required.', verbose_name='Allow Valid Time End?'),
        ),
        migrations.AlterField(
            model_name='referencerange',
            name='ct_id',
            field=models.CharField(default='cjieyi2c80000k4l342jqwh9n', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='referencerange',
            name='ui_type',
            field=models.CharField(choices=[('choose', 'Choose Type:'), ('input', 'Input Box'), ('dropdown', 'Dropdown'), ('radiogroup', 'Radio Button Group'), ('radio', 'Radio Button'), ('checkbox', 'Checkbox(es)')], default='Choose UI Type:', help_text='Choose the preferred UI Type for this component. Use UX best practices. Be aware that the generator may override your selection.', max_length=40, verbose_name='Preferred UI Type'),
        ),
        migrations.AlterField(
            model_name='referencerange',
            name='validate',
            field=models.BooleanField(default=False, help_text='Hard validation is when the UI enforces criteria on input fields. Soft validation allows users to input any value, warns them when it is not within parameters of the component. Then offers to allow correction or select an Exceptional Value as explaination.', verbose_name='Hard Validate?'),
        ),
        migrations.AlterField(
            model_name='simplereferencerange',
            name='adapter_ctid',
            field=models.CharField(default='cjieyi2cb0001k4l3axg0o0f4', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='simplereferencerange',
            name='allow_location',
            field=models.BooleanField(default=False, help_text='Check this box to allow a decimal longitude and latitude location even when not required.', verbose_name='Allow Location?'),
        ),
        migrations.AlterField(
            model_name='simplereferencerange',
            name='allow_mod',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time for last modified element even when not required.', verbose_name='Allow Time Modified?'),
        ),
        migrations.AlterField(
            model_name='simplereferencerange',
            name='allow_tr',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time Recorded element even when not required.', verbose_name='Allow Time Recorded?'),
        ),
        migrations.AlterField(
            model_name='simplereferencerange',
            name='allow_vtb',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time Begin element even when not required.', verbose_name='Allow Valid Time Begin?'),
        ),
        migrations.AlterField(
            model_name='simplereferencerange',
            name='allow_vte',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time End element even when not required.', verbose_name='Allow Valid Time End?'),
        ),
        migrations.AlterField(
            model_name='simplereferencerange',
            name='ct_id',
            field=models.CharField(default='cjieyi2c80000k4l342jqwh9n', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='simplereferencerange',
            name='ui_type',
            field=models.CharField(choices=[('choose', 'Choose Type:'), ('input', 'Input Box'), ('dropdown', 'Dropdown'), ('radiogroup', 'Radio Button Group'), ('radio', 'Radio Button'), ('checkbox', 'Checkbox(es)')], default='Choose UI Type:', help_text='Choose the preferred UI Type for this component. Use UX best practices. Be aware that the generator may override your selection.', max_length=40, verbose_name='Preferred UI Type'),
        ),
        migrations.AlterField(
            model_name='simplereferencerange',
            name='validate',
            field=models.BooleanField(default=False, help_text='Hard validation is when the UI enforces criteria on input fields. Soft validation allows users to input any value, warns them when it is not within parameters of the component. Then offers to allow correction or select an Exceptional Value as explaination.', verbose_name='Hard Validate?'),
        ),
        migrations.AlterField(
            model_name='units',
            name='adapter_ctid',
            field=models.CharField(default='cjieyi2cb0001k4l3axg0o0f4', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='units',
            name='allow_location',
            field=models.BooleanField(default=False, help_text='Check this box to allow a decimal longitude and latitude location even when not required.', verbose_name='Allow Location?'),
        ),
        migrations.AlterField(
            model_name='units',
            name='allow_mod',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time for last modified element even when not required.', verbose_name='Allow Time Modified?'),
        ),
        migrations.AlterField(
            model_name='units',
            name='allow_tr',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time Recorded element even when not required.', verbose_name='Allow Time Recorded?'),
        ),
        migrations.AlterField(
            model_name='units',
            name='allow_vtb',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time Begin element even when not required.', verbose_name='Allow Valid Time Begin?'),
        ),
        migrations.AlterField(
            model_name='units',
            name='allow_vte',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time End element even when not required.', verbose_name='Allow Valid Time End?'),
        ),
        migrations.AlterField(
            model_name='units',
            name='ct_id',
            field=models.CharField(default='cjieyi2c80000k4l342jqwh9n', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='units',
            name='ui_type',
            field=models.CharField(choices=[('choose', 'Choose Type:'), ('input', 'Input Box'), ('dropdown', 'Dropdown'), ('radiogroup', 'Radio Button Group'), ('radio', 'Radio Button'), ('checkbox', 'Checkbox(es)')], default='Choose UI Type:', help_text='Choose the preferred UI Type for this component. Use UX best practices. Be aware that the generator may override your selection.', max_length=40, verbose_name='Preferred UI Type'),
        ),
        migrations.AlterField(
            model_name='units',
            name='validate',
            field=models.BooleanField(default=False, help_text='Hard validation is when the UI enforces criteria on input fields. Soft validation allows users to input any value, warns them when it is not within parameters of the component. Then offers to allow correction or select an Exceptional Value as explaination.', verbose_name='Hard Validate?'),
        ),
        migrations.AlterField(
            model_name='xdboolean',
            name='adapter_ctid',
            field=models.CharField(default='cjieyi2cb0001k4l3axg0o0f4', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdboolean',
            name='allow_location',
            field=models.BooleanField(default=False, help_text='Check this box to allow a decimal longitude and latitude location even when not required.', verbose_name='Allow Location?'),
        ),
        migrations.AlterField(
            model_name='xdboolean',
            name='allow_mod',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time for last modified element even when not required.', verbose_name='Allow Time Modified?'),
        ),
        migrations.AlterField(
            model_name='xdboolean',
            name='allow_tr',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time Recorded element even when not required.', verbose_name='Allow Time Recorded?'),
        ),
        migrations.AlterField(
            model_name='xdboolean',
            name='allow_vtb',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time Begin element even when not required.', verbose_name='Allow Valid Time Begin?'),
        ),
        migrations.AlterField(
            model_name='xdboolean',
            name='allow_vte',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time End element even when not required.', verbose_name='Allow Valid Time End?'),
        ),
        migrations.AlterField(
            model_name='xdboolean',
            name='ct_id',
            field=models.CharField(default='cjieyi2c80000k4l342jqwh9n', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdboolean',
            name='ui_type',
            field=models.CharField(choices=[('choose', 'Choose Type:'), ('input', 'Input Box'), ('dropdown', 'Dropdown'), ('radiogroup', 'Radio Button Group'), ('radio', 'Radio Button'), ('checkbox', 'Checkbox(es)')], default='Choose UI Type:', help_text='Choose the preferred UI Type for this component. Use UX best practices. Be aware that the generator may override your selection.', max_length=40, verbose_name='Preferred UI Type'),
        ),
        migrations.AlterField(
            model_name='xdboolean',
            name='validate',
            field=models.BooleanField(default=False, help_text='Hard validation is when the UI enforces criteria on input fields. Soft validation allows users to input any value, warns them when it is not within parameters of the component. Then offers to allow correction or select an Exceptional Value as explaination.', verbose_name='Hard Validate?'),
        ),
        migrations.AlterField(
            model_name='xdcount',
            name='adapter_ctid',
            field=models.CharField(default='cjieyi2cb0001k4l3axg0o0f4', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdcount',
            name='allow_location',
            field=models.BooleanField(default=False, help_text='Check this box to allow a decimal longitude and latitude location even when not required.', verbose_name='Allow Location?'),
        ),
        migrations.AlterField(
            model_name='xdcount',
            name='allow_mod',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time for last modified element even when not required.', verbose_name='Allow Time Modified?'),
        ),
        migrations.AlterField(
            model_name='xdcount',
            name='allow_tr',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time Recorded element even when not required.', verbose_name='Allow Time Recorded?'),
        ),
        migrations.AlterField(
            model_name='xdcount',
            name='allow_vtb',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time Begin element even when not required.', verbose_name='Allow Valid Time Begin?'),
        ),
        migrations.AlterField(
            model_name='xdcount',
            name='allow_vte',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time End element even when not required.', verbose_name='Allow Valid Time End?'),
        ),
        migrations.AlterField(
            model_name='xdcount',
            name='ct_id',
            field=models.CharField(default='cjieyi2c80000k4l342jqwh9n', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdcount',
            name='ui_type',
            field=models.CharField(choices=[('choose', 'Choose Type:'), ('input', 'Input Box'), ('dropdown', 'Dropdown'), ('radiogroup', 'Radio Button Group'), ('radio', 'Radio Button'), ('checkbox', 'Checkbox(es)')], default='Choose UI Type:', help_text='Choose the preferred UI Type for this component. Use UX best practices. Be aware that the generator may override your selection.', max_length=40, verbose_name='Preferred UI Type'),
        ),
        migrations.AlterField(
            model_name='xdcount',
            name='validate',
            field=models.BooleanField(default=False, help_text='Hard validation is when the UI enforces criteria on input fields. Soft validation allows users to input any value, warns them when it is not within parameters of the component. Then offers to allow correction or select an Exceptional Value as explaination.', verbose_name='Hard Validate?'),
        ),
        migrations.AlterField(
            model_name='xdfile',
            name='adapter_ctid',
            field=models.CharField(default='cjieyi2cb0001k4l3axg0o0f4', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdfile',
            name='allow_location',
            field=models.BooleanField(default=False, help_text='Check this box to allow a decimal longitude and latitude location even when not required.', verbose_name='Allow Location?'),
        ),
        migrations.AlterField(
            model_name='xdfile',
            name='allow_mod',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time for last modified element even when not required.', verbose_name='Allow Time Modified?'),
        ),
        migrations.AlterField(
            model_name='xdfile',
            name='allow_tr',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time Recorded element even when not required.', verbose_name='Allow Time Recorded?'),
        ),
        migrations.AlterField(
            model_name='xdfile',
            name='allow_vtb',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time Begin element even when not required.', verbose_name='Allow Valid Time Begin?'),
        ),
        migrations.AlterField(
            model_name='xdfile',
            name='allow_vte',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time End element even when not required.', verbose_name='Allow Valid Time End?'),
        ),
        migrations.AlterField(
            model_name='xdfile',
            name='ct_id',
            field=models.CharField(default='cjieyi2c80000k4l342jqwh9n', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdfile',
            name='ui_type',
            field=models.CharField(choices=[('choose', 'Choose Type:'), ('input', 'Input Box'), ('dropdown', 'Dropdown'), ('radiogroup', 'Radio Button Group'), ('radio', 'Radio Button'), ('checkbox', 'Checkbox(es)')], default='Choose UI Type:', help_text='Choose the preferred UI Type for this component. Use UX best practices. Be aware that the generator may override your selection.', max_length=40, verbose_name='Preferred UI Type'),
        ),
        migrations.AlterField(
            model_name='xdfile',
            name='validate',
            field=models.BooleanField(default=False, help_text='Hard validation is when the UI enforces criteria on input fields. Soft validation allows users to input any value, warns them when it is not within parameters of the component. Then offers to allow correction or select an Exceptional Value as explaination.', verbose_name='Hard Validate?'),
        ),
        migrations.AlterField(
            model_name='xdfloat',
            name='adapter_ctid',
            field=models.CharField(default='cjieyi2cb0001k4l3axg0o0f4', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdfloat',
            name='allow_location',
            field=models.BooleanField(default=False, help_text='Check this box to allow a decimal longitude and latitude location even when not required.', verbose_name='Allow Location?'),
        ),
        migrations.AlterField(
            model_name='xdfloat',
            name='allow_mod',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time for last modified element even when not required.', verbose_name='Allow Time Modified?'),
        ),
        migrations.AlterField(
            model_name='xdfloat',
            name='allow_tr',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time Recorded element even when not required.', verbose_name='Allow Time Recorded?'),
        ),
        migrations.AlterField(
            model_name='xdfloat',
            name='allow_vtb',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time Begin element even when not required.', verbose_name='Allow Valid Time Begin?'),
        ),
        migrations.AlterField(
            model_name='xdfloat',
            name='allow_vte',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time End element even when not required.', verbose_name='Allow Valid Time End?'),
        ),
        migrations.AlterField(
            model_name='xdfloat',
            name='ct_id',
            field=models.CharField(default='cjieyi2c80000k4l342jqwh9n', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdfloat',
            name='ui_type',
            field=models.CharField(choices=[('choose', 'Choose Type:'), ('input', 'Input Box'), ('dropdown', 'Dropdown'), ('radiogroup', 'Radio Button Group'), ('radio', 'Radio Button'), ('checkbox', 'Checkbox(es)')], default='Choose UI Type:', help_text='Choose the preferred UI Type for this component. Use UX best practices. Be aware that the generator may override your selection.', max_length=40, verbose_name='Preferred UI Type'),
        ),
        migrations.AlterField(
            model_name='xdfloat',
            name='validate',
            field=models.BooleanField(default=False, help_text='Hard validation is when the UI enforces criteria on input fields. Soft validation allows users to input any value, warns them when it is not within parameters of the component. Then offers to allow correction or select an Exceptional Value as explaination.', verbose_name='Hard Validate?'),
        ),
        migrations.AlterField(
            model_name='xdinterval',
            name='adapter_ctid',
            field=models.CharField(default='cjieyi2cb0001k4l3axg0o0f4', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdinterval',
            name='allow_location',
            field=models.BooleanField(default=False, help_text='Check this box to allow a decimal longitude and latitude location even when not required.', verbose_name='Allow Location?'),
        ),
        migrations.AlterField(
            model_name='xdinterval',
            name='allow_mod',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time for last modified element even when not required.', verbose_name='Allow Time Modified?'),
        ),
        migrations.AlterField(
            model_name='xdinterval',
            name='allow_tr',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time Recorded element even when not required.', verbose_name='Allow Time Recorded?'),
        ),
        migrations.AlterField(
            model_name='xdinterval',
            name='allow_vtb',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time Begin element even when not required.', verbose_name='Allow Valid Time Begin?'),
        ),
        migrations.AlterField(
            model_name='xdinterval',
            name='allow_vte',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time End element even when not required.', verbose_name='Allow Valid Time End?'),
        ),
        migrations.AlterField(
            model_name='xdinterval',
            name='ct_id',
            field=models.CharField(default='cjieyi2c80000k4l342jqwh9n', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdinterval',
            name='ui_type',
            field=models.CharField(choices=[('choose', 'Choose Type:'), ('input', 'Input Box'), ('dropdown', 'Dropdown'), ('radiogroup', 'Radio Button Group'), ('radio', 'Radio Button'), ('checkbox', 'Checkbox(es)')], default='Choose UI Type:', help_text='Choose the preferred UI Type for this component. Use UX best practices. Be aware that the generator may override your selection.', max_length=40, verbose_name='Preferred UI Type'),
        ),
        migrations.AlterField(
            model_name='xdinterval',
            name='validate',
            field=models.BooleanField(default=False, help_text='Hard validation is when the UI enforces criteria on input fields. Soft validation allows users to input any value, warns them when it is not within parameters of the component. Then offers to allow correction or select an Exceptional Value as explaination.', verbose_name='Hard Validate?'),
        ),
        migrations.AlterField(
            model_name='xdlink',
            name='adapter_ctid',
            field=models.CharField(default='cjieyi2cb0001k4l3axg0o0f4', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdlink',
            name='allow_location',
            field=models.BooleanField(default=False, help_text='Check this box to allow a decimal longitude and latitude location even when not required.', verbose_name='Allow Location?'),
        ),
        migrations.AlterField(
            model_name='xdlink',
            name='allow_mod',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time for last modified element even when not required.', verbose_name='Allow Time Modified?'),
        ),
        migrations.AlterField(
            model_name='xdlink',
            name='allow_tr',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time Recorded element even when not required.', verbose_name='Allow Time Recorded?'),
        ),
        migrations.AlterField(
            model_name='xdlink',
            name='allow_vtb',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time Begin element even when not required.', verbose_name='Allow Valid Time Begin?'),
        ),
        migrations.AlterField(
            model_name='xdlink',
            name='allow_vte',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time End element even when not required.', verbose_name='Allow Valid Time End?'),
        ),
        migrations.AlterField(
            model_name='xdlink',
            name='ct_id',
            field=models.CharField(default='cjieyi2c80000k4l342jqwh9n', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdlink',
            name='ui_type',
            field=models.CharField(choices=[('choose', 'Choose Type:'), ('input', 'Input Box'), ('dropdown', 'Dropdown'), ('radiogroup', 'Radio Button Group'), ('radio', 'Radio Button'), ('checkbox', 'Checkbox(es)')], default='Choose UI Type:', help_text='Choose the preferred UI Type for this component. Use UX best practices. Be aware that the generator may override your selection.', max_length=40, verbose_name='Preferred UI Type'),
        ),
        migrations.AlterField(
            model_name='xdlink',
            name='validate',
            field=models.BooleanField(default=False, help_text='Hard validation is when the UI enforces criteria on input fields. Soft validation allows users to input any value, warns them when it is not within parameters of the component. Then offers to allow correction or select an Exceptional Value as explaination.', verbose_name='Hard Validate?'),
        ),
        migrations.AlterField(
            model_name='xdordinal',
            name='adapter_ctid',
            field=models.CharField(default='cjieyi2cb0001k4l3axg0o0f4', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdordinal',
            name='allow_location',
            field=models.BooleanField(default=False, help_text='Check this box to allow a decimal longitude and latitude location even when not required.', verbose_name='Allow Location?'),
        ),
        migrations.AlterField(
            model_name='xdordinal',
            name='allow_mod',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time for last modified element even when not required.', verbose_name='Allow Time Modified?'),
        ),
        migrations.AlterField(
            model_name='xdordinal',
            name='allow_tr',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time Recorded element even when not required.', verbose_name='Allow Time Recorded?'),
        ),
        migrations.AlterField(
            model_name='xdordinal',
            name='allow_vtb',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time Begin element even when not required.', verbose_name='Allow Valid Time Begin?'),
        ),
        migrations.AlterField(
            model_name='xdordinal',
            name='allow_vte',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time End element even when not required.', verbose_name='Allow Valid Time End?'),
        ),
        migrations.AlterField(
            model_name='xdordinal',
            name='ct_id',
            field=models.CharField(default='cjieyi2c80000k4l342jqwh9n', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdordinal',
            name='ui_type',
            field=models.CharField(choices=[('choose', 'Choose Type:'), ('input', 'Input Box'), ('dropdown', 'Dropdown'), ('radiogroup', 'Radio Button Group'), ('radio', 'Radio Button'), ('checkbox', 'Checkbox(es)')], default='Choose UI Type:', help_text='Choose the preferred UI Type for this component. Use UX best practices. Be aware that the generator may override your selection.', max_length=40, verbose_name='Preferred UI Type'),
        ),
        migrations.AlterField(
            model_name='xdordinal',
            name='validate',
            field=models.BooleanField(default=False, help_text='Hard validation is when the UI enforces criteria on input fields. Soft validation allows users to input any value, warns them when it is not within parameters of the component. Then offers to allow correction or select an Exceptional Value as explaination.', verbose_name='Hard Validate?'),
        ),
        migrations.AlterField(
            model_name='xdquantity',
            name='adapter_ctid',
            field=models.CharField(default='cjieyi2cb0001k4l3axg0o0f4', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdquantity',
            name='allow_location',
            field=models.BooleanField(default=False, help_text='Check this box to allow a decimal longitude and latitude location even when not required.', verbose_name='Allow Location?'),
        ),
        migrations.AlterField(
            model_name='xdquantity',
            name='allow_mod',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time for last modified element even when not required.', verbose_name='Allow Time Modified?'),
        ),
        migrations.AlterField(
            model_name='xdquantity',
            name='allow_tr',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time Recorded element even when not required.', verbose_name='Allow Time Recorded?'),
        ),
        migrations.AlterField(
            model_name='xdquantity',
            name='allow_vtb',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time Begin element even when not required.', verbose_name='Allow Valid Time Begin?'),
        ),
        migrations.AlterField(
            model_name='xdquantity',
            name='allow_vte',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time End element even when not required.', verbose_name='Allow Valid Time End?'),
        ),
        migrations.AlterField(
            model_name='xdquantity',
            name='ct_id',
            field=models.CharField(default='cjieyi2c80000k4l342jqwh9n', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdquantity',
            name='ui_type',
            field=models.CharField(choices=[('choose', 'Choose Type:'), ('input', 'Input Box'), ('dropdown', 'Dropdown'), ('radiogroup', 'Radio Button Group'), ('radio', 'Radio Button'), ('checkbox', 'Checkbox(es)')], default='Choose UI Type:', help_text='Choose the preferred UI Type for this component. Use UX best practices. Be aware that the generator may override your selection.', max_length=40, verbose_name='Preferred UI Type'),
        ),
        migrations.AlterField(
            model_name='xdquantity',
            name='validate',
            field=models.BooleanField(default=False, help_text='Hard validation is when the UI enforces criteria on input fields. Soft validation allows users to input any value, warns them when it is not within parameters of the component. Then offers to allow correction or select an Exceptional Value as explaination.', verbose_name='Hard Validate?'),
        ),
        migrations.AlterField(
            model_name='xdratio',
            name='adapter_ctid',
            field=models.CharField(default='cjieyi2cb0001k4l3axg0o0f4', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdratio',
            name='allow_location',
            field=models.BooleanField(default=False, help_text='Check this box to allow a decimal longitude and latitude location even when not required.', verbose_name='Allow Location?'),
        ),
        migrations.AlterField(
            model_name='xdratio',
            name='allow_mod',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time for last modified element even when not required.', verbose_name='Allow Time Modified?'),
        ),
        migrations.AlterField(
            model_name='xdratio',
            name='allow_tr',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time Recorded element even when not required.', verbose_name='Allow Time Recorded?'),
        ),
        migrations.AlterField(
            model_name='xdratio',
            name='allow_vtb',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time Begin element even when not required.', verbose_name='Allow Valid Time Begin?'),
        ),
        migrations.AlterField(
            model_name='xdratio',
            name='allow_vte',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time End element even when not required.', verbose_name='Allow Valid Time End?'),
        ),
        migrations.AlterField(
            model_name='xdratio',
            name='ct_id',
            field=models.CharField(default='cjieyi2c80000k4l342jqwh9n', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdratio',
            name='ui_type',
            field=models.CharField(choices=[('choose', 'Choose Type:'), ('input', 'Input Box'), ('dropdown', 'Dropdown'), ('radiogroup', 'Radio Button Group'), ('radio', 'Radio Button'), ('checkbox', 'Checkbox(es)')], default='Choose UI Type:', help_text='Choose the preferred UI Type for this component. Use UX best practices. Be aware that the generator may override your selection.', max_length=40, verbose_name='Preferred UI Type'),
        ),
        migrations.AlterField(
            model_name='xdratio',
            name='validate',
            field=models.BooleanField(default=False, help_text='Hard validation is when the UI enforces criteria on input fields. Soft validation allows users to input any value, warns them when it is not within parameters of the component. Then offers to allow correction or select an Exceptional Value as explaination.', verbose_name='Hard Validate?'),
        ),
        migrations.AlterField(
            model_name='xdstring',
            name='adapter_ctid',
            field=models.CharField(default='cjieyi2cb0001k4l3axg0o0f4', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdstring',
            name='allow_location',
            field=models.BooleanField(default=False, help_text='Check this box to allow a decimal longitude and latitude location even when not required.', verbose_name='Allow Location?'),
        ),
        migrations.AlterField(
            model_name='xdstring',
            name='allow_mod',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time for last modified element even when not required.', verbose_name='Allow Time Modified?'),
        ),
        migrations.AlterField(
            model_name='xdstring',
            name='allow_tr',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time Recorded element even when not required.', verbose_name='Allow Time Recorded?'),
        ),
        migrations.AlterField(
            model_name='xdstring',
            name='allow_vtb',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time Begin element even when not required.', verbose_name='Allow Valid Time Begin?'),
        ),
        migrations.AlterField(
            model_name='xdstring',
            name='allow_vte',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time End element even when not required.', verbose_name='Allow Valid Time End?'),
        ),
        migrations.AlterField(
            model_name='xdstring',
            name='ct_id',
            field=models.CharField(default='cjieyi2c80000k4l342jqwh9n', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdstring',
            name='ui_type',
            field=models.CharField(choices=[('choose', 'Choose Type:'), ('input', 'Input Box'), ('dropdown', 'Dropdown'), ('radiogroup', 'Radio Button Group'), ('radio', 'Radio Button'), ('checkbox', 'Checkbox(es)')], default='Choose UI Type:', help_text='Choose the preferred UI Type for this component. Use UX best practices. Be aware that the generator may override your selection.', max_length=40, verbose_name='Preferred UI Type'),
        ),
        migrations.AlterField(
            model_name='xdstring',
            name='validate',
            field=models.BooleanField(default=False, help_text='Hard validation is when the UI enforces criteria on input fields. Soft validation allows users to input any value, warns them when it is not within parameters of the component. Then offers to allow correction or select an Exceptional Value as explaination.', verbose_name='Hard Validate?'),
        ),
        migrations.AlterField(
            model_name='xdtemporal',
            name='adapter_ctid',
            field=models.CharField(default='cjieyi2cb0001k4l3axg0o0f4', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdtemporal',
            name='allow_location',
            field=models.BooleanField(default=False, help_text='Check this box to allow a decimal longitude and latitude location even when not required.', verbose_name='Allow Location?'),
        ),
        migrations.AlterField(
            model_name='xdtemporal',
            name='allow_mod',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time for last modified element even when not required.', verbose_name='Allow Time Modified?'),
        ),
        migrations.AlterField(
            model_name='xdtemporal',
            name='allow_tr',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Date & Time Recorded element even when not required.', verbose_name='Allow Time Recorded?'),
        ),
        migrations.AlterField(
            model_name='xdtemporal',
            name='allow_vtb',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time Begin element even when not required.', verbose_name='Allow Valid Time Begin?'),
        ),
        migrations.AlterField(
            model_name='xdtemporal',
            name='allow_vte',
            field=models.BooleanField(default=False, help_text='Check this box to allow a Valid Time End element even when not required.', verbose_name='Allow Valid Time End?'),
        ),
        migrations.AlterField(
            model_name='xdtemporal',
            name='ct_id',
            field=models.CharField(default='cjieyi2c80000k4l342jqwh9n', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdtemporal',
            name='ui_type',
            field=models.CharField(choices=[('choose', 'Choose Type:'), ('input', 'Input Box'), ('dropdown', 'Dropdown'), ('radiogroup', 'Radio Button Group'), ('radio', 'Radio Button'), ('checkbox', 'Checkbox(es)')], default='Choose UI Type:', help_text='Choose the preferred UI Type for this component. Use UX best practices. Be aware that the generator may override your selection.', max_length=40, verbose_name='Preferred UI Type'),
        ),
        migrations.AlterField(
            model_name='xdtemporal',
            name='validate',
            field=models.BooleanField(default=False, help_text='Hard validation is when the UI enforces criteria on input fields. Soft validation allows users to input any value, warns them when it is not within parameters of the component. Then offers to allow correction or select an Exceptional Value as explaination.', verbose_name='Hard Validate?'),
        ),
    ]
