# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmgen', '0002_auto_20170509_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='audit',
            field=models.ManyToManyField(blank=True, help_text='Audit structure to provide audit trail tracking of information.', to='dmgen.Audit', verbose_name='audit'),
        ),
    ]
