# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmgen', '0003_auto_20170509_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dm',
            name='about',
            field=models.CharField(default='http://dmgen.s3model.com/dmlib/', help_text="The URL to the DM after publication. The DM ID will be added after the trailing slash in the format of 'dm-{dm_id}.xsd' This provides a full path and filename for the dm as a unique identifier.", max_length=255, verbose_name='about'),
        ),
        migrations.AlterField(
            model_name='dm',
            name='dc_type',
            field=models.CharField(default='S3Model Data Model (DM)', editable=False, max_length=110, verbose_name='type'),
        ),
    ]
