# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmgen', '0005_auto_20170617_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xdtemporal',
            name='allow_datetimestamp',
        ),
        migrations.RemoveField(
            model_name='xdtemporal',
            name='allow_dtduration',
        ),
        migrations.RemoveField(
            model_name='xdtemporal',
            name='allow_ymduration',
        ),
    ]
