# Generated by Django 2.0.3 on 2018-03-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmgen', '0012_auto_20180325_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='attestation',
            name='ct_id',
            field=models.CharField(default='cjf7dacd50000vfl3qqnikx2f', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AddField(
            model_name='audit',
            name='ct_id',
            field=models.CharField(default='cjf7dacd50000vfl3qqnikx2f', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='ct_id',
            field=models.CharField(default='cjf7dacd50000vfl3qqnikx2f', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AddField(
            model_name='dm',
            name='ct_id',
            field=models.CharField(default='cjf7dacei0004vfl33o68ybue', editable=False, help_text='The unique identifier for the DM.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AddField(
            model_name='participation',
            name='ct_id',
            field=models.CharField(default='cjf7dacd50000vfl3qqnikx2f', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AddField(
            model_name='party',
            name='ct_id',
            field=models.CharField(default='cjf7dacd50000vfl3qqnikx2f', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AddField(
            model_name='referencerange',
            name='adapter_ctid',
            field=models.CharField(default='cjf7dacd60002vfl3r7yq1g41', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AddField(
            model_name='referencerange',
            name='ct_id',
            field=models.CharField(default='cjf7dacd50000vfl3qqnikx2f', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AddField(
            model_name='simplereferencerange',
            name='adapter_ctid',
            field=models.CharField(default='cjf7dacd60002vfl3r7yq1g41', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AddField(
            model_name='simplereferencerange',
            name='ct_id',
            field=models.CharField(default='cjf7dacd50000vfl3qqnikx2f', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AddField(
            model_name='units',
            name='adapter_ctid',
            field=models.CharField(default='cjf7dacd60002vfl3r7yq1g41', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AddField(
            model_name='units',
            name='ct_id',
            field=models.CharField(default='cjf7dacd50000vfl3qqnikx2f', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AddField(
            model_name='xdboolean',
            name='adapter_ctid',
            field=models.CharField(default='cjf7dacd60002vfl3r7yq1g41', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AddField(
            model_name='xdboolean',
            name='ct_id',
            field=models.CharField(default='cjf7dacd50000vfl3qqnikx2f', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AddField(
            model_name='xdcount',
            name='adapter_ctid',
            field=models.CharField(default='cjf7dacd60002vfl3r7yq1g41', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AddField(
            model_name='xdcount',
            name='ct_id',
            field=models.CharField(default='cjf7dacd50000vfl3qqnikx2f', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AddField(
            model_name='xdfile',
            name='adapter_ctid',
            field=models.CharField(default='cjf7dacd60002vfl3r7yq1g41', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AddField(
            model_name='xdfile',
            name='ct_id',
            field=models.CharField(default='cjf7dacd50000vfl3qqnikx2f', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AddField(
            model_name='xdfloat',
            name='adapter_ctid',
            field=models.CharField(default='cjf7dacd60002vfl3r7yq1g41', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AddField(
            model_name='xdfloat',
            name='ct_id',
            field=models.CharField(default='cjf7dacd50000vfl3qqnikx2f', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AddField(
            model_name='xdinterval',
            name='adapter_ctid',
            field=models.CharField(default='cjf7dacd60002vfl3r7yq1g41', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AddField(
            model_name='xdinterval',
            name='ct_id',
            field=models.CharField(default='cjf7dacd50000vfl3qqnikx2f', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AddField(
            model_name='xdlink',
            name='adapter_ctid',
            field=models.CharField(default='cjf7dacd60002vfl3r7yq1g41', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AddField(
            model_name='xdlink',
            name='ct_id',
            field=models.CharField(default='cjf7dacd50000vfl3qqnikx2f', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AddField(
            model_name='xdordinal',
            name='adapter_ctid',
            field=models.CharField(default='cjf7dacd60002vfl3r7yq1g41', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AddField(
            model_name='xdordinal',
            name='ct_id',
            field=models.CharField(default='cjf7dacd50000vfl3qqnikx2f', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AddField(
            model_name='xdquantity',
            name='adapter_ctid',
            field=models.CharField(default='cjf7dacd60002vfl3r7yq1g41', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AddField(
            model_name='xdquantity',
            name='ct_id',
            field=models.CharField(default='cjf7dacd50000vfl3qqnikx2f', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AddField(
            model_name='xdratio',
            name='adapter_ctid',
            field=models.CharField(default='cjf7dacd60002vfl3r7yq1g41', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AddField(
            model_name='xdratio',
            name='ct_id',
            field=models.CharField(default='cjf7dacd50000vfl3qqnikx2f', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AddField(
            model_name='xdstring',
            name='adapter_ctid',
            field=models.CharField(default='cjf7dacd60002vfl3r7yq1g41', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AddField(
            model_name='xdstring',
            name='ct_id',
            field=models.CharField(default='cjf7dacd50000vfl3qqnikx2f', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AddField(
            model_name='xdtemporal',
            name='adapter_ctid',
            field=models.CharField(default='cjf7dacd60002vfl3r7yq1g41', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AddField(
            model_name='xdtemporal',
            name='ct_id',
            field=models.CharField(default='cjf7dacd50000vfl3qqnikx2f', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='attestation',
            name='cuid',
            field=models.CharField(default='cjf7dacd50001vfl3o37m7vdo', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='cuid',
            field=models.CharField(default='cjf7dacd50001vfl3o37m7vdo', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='cuid',
            field=models.CharField(default='cjf7dacd50001vfl3o37m7vdo', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='dm',
            name='cuid',
            field=models.CharField(default='cjf7dacej0005vfl3gjr44slh', editable=False, help_text='The unique identifier for the DM.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='dm',
            name='title',
            field=models.CharField(help_text='Enter the name of this Data Model (DM).', max_length=255, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='cuid',
            field=models.CharField(default='cjf7dacd50001vfl3o37m7vdo', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='party',
            name='cuid',
            field=models.CharField(default='cjf7dacd50001vfl3o37m7vdo', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='referencerange',
            name='adapter_cuid',
            field=models.CharField(default='cjf7dacd70003vfl39qzd5qrq', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='referencerange',
            name='cuid',
            field=models.CharField(default='cjf7dacd50001vfl3o37m7vdo', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='simplereferencerange',
            name='adapter_cuid',
            field=models.CharField(default='cjf7dacd70003vfl39qzd5qrq', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='simplereferencerange',
            name='cuid',
            field=models.CharField(default='cjf7dacd50001vfl3o37m7vdo', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='units',
            name='adapter_cuid',
            field=models.CharField(default='cjf7dacd70003vfl39qzd5qrq', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='units',
            name='cuid',
            field=models.CharField(default='cjf7dacd50001vfl3o37m7vdo', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdboolean',
            name='adapter_cuid',
            field=models.CharField(default='cjf7dacd70003vfl39qzd5qrq', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdboolean',
            name='cuid',
            field=models.CharField(default='cjf7dacd50001vfl3o37m7vdo', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdcount',
            name='adapter_cuid',
            field=models.CharField(default='cjf7dacd70003vfl39qzd5qrq', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdcount',
            name='cuid',
            field=models.CharField(default='cjf7dacd50001vfl3o37m7vdo', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdfile',
            name='adapter_cuid',
            field=models.CharField(default='cjf7dacd70003vfl39qzd5qrq', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdfile',
            name='cuid',
            field=models.CharField(default='cjf7dacd50001vfl3o37m7vdo', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdfloat',
            name='adapter_cuid',
            field=models.CharField(default='cjf7dacd70003vfl39qzd5qrq', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdfloat',
            name='cuid',
            field=models.CharField(default='cjf7dacd50001vfl3o37m7vdo', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdinterval',
            name='adapter_cuid',
            field=models.CharField(default='cjf7dacd70003vfl39qzd5qrq', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdinterval',
            name='cuid',
            field=models.CharField(default='cjf7dacd50001vfl3o37m7vdo', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdlink',
            name='adapter_cuid',
            field=models.CharField(default='cjf7dacd70003vfl39qzd5qrq', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdlink',
            name='cuid',
            field=models.CharField(default='cjf7dacd50001vfl3o37m7vdo', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdordinal',
            name='adapter_cuid',
            field=models.CharField(default='cjf7dacd70003vfl39qzd5qrq', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdordinal',
            name='cuid',
            field=models.CharField(default='cjf7dacd50001vfl3o37m7vdo', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdquantity',
            name='adapter_cuid',
            field=models.CharField(default='cjf7dacd70003vfl39qzd5qrq', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdquantity',
            name='cuid',
            field=models.CharField(default='cjf7dacd50001vfl3o37m7vdo', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdratio',
            name='adapter_cuid',
            field=models.CharField(default='cjf7dacd70003vfl39qzd5qrq', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdratio',
            name='cuid',
            field=models.CharField(default='cjf7dacd50001vfl3o37m7vdo', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdstring',
            name='adapter_cuid',
            field=models.CharField(default='cjf7dacd70003vfl39qzd5qrq', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdstring',
            name='cuid',
            field=models.CharField(default='cjf7dacd50001vfl3o37m7vdo', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdtemporal',
            name='adapter_cuid',
            field=models.CharField(default='cjf7dacd70003vfl39qzd5qrq', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdtemporal',
            name='cuid',
            field=models.CharField(default='cjf7dacd50001vfl3o37m7vdo', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
    ]
