# Generated by Django 2.0.3 on 2018-03-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmgen', '0013_auto_20180325_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attestation',
            name='cuid',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='cuid',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='cuid',
        ),
        migrations.RemoveField(
            model_name='dm',
            name='cuid',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='cuid',
        ),
        migrations.RemoveField(
            model_name='party',
            name='cuid',
        ),
        migrations.RemoveField(
            model_name='referencerange',
            name='adapter_cuid',
        ),
        migrations.RemoveField(
            model_name='referencerange',
            name='cuid',
        ),
        migrations.RemoveField(
            model_name='simplereferencerange',
            name='adapter_cuid',
        ),
        migrations.RemoveField(
            model_name='simplereferencerange',
            name='cuid',
        ),
        migrations.RemoveField(
            model_name='units',
            name='adapter_cuid',
        ),
        migrations.RemoveField(
            model_name='units',
            name='cuid',
        ),
        migrations.RemoveField(
            model_name='xdboolean',
            name='adapter_cuid',
        ),
        migrations.RemoveField(
            model_name='xdboolean',
            name='cuid',
        ),
        migrations.RemoveField(
            model_name='xdcount',
            name='adapter_cuid',
        ),
        migrations.RemoveField(
            model_name='xdcount',
            name='cuid',
        ),
        migrations.RemoveField(
            model_name='xdfile',
            name='adapter_cuid',
        ),
        migrations.RemoveField(
            model_name='xdfile',
            name='cuid',
        ),
        migrations.RemoveField(
            model_name='xdfloat',
            name='adapter_cuid',
        ),
        migrations.RemoveField(
            model_name='xdfloat',
            name='cuid',
        ),
        migrations.RemoveField(
            model_name='xdinterval',
            name='adapter_cuid',
        ),
        migrations.RemoveField(
            model_name='xdinterval',
            name='cuid',
        ),
        migrations.RemoveField(
            model_name='xdlink',
            name='adapter_cuid',
        ),
        migrations.RemoveField(
            model_name='xdlink',
            name='cuid',
        ),
        migrations.RemoveField(
            model_name='xdordinal',
            name='adapter_cuid',
        ),
        migrations.RemoveField(
            model_name='xdordinal',
            name='cuid',
        ),
        migrations.RemoveField(
            model_name='xdquantity',
            name='adapter_cuid',
        ),
        migrations.RemoveField(
            model_name='xdquantity',
            name='cuid',
        ),
        migrations.RemoveField(
            model_name='xdratio',
            name='adapter_cuid',
        ),
        migrations.RemoveField(
            model_name='xdratio',
            name='cuid',
        ),
        migrations.RemoveField(
            model_name='xdstring',
            name='adapter_cuid',
        ),
        migrations.RemoveField(
            model_name='xdstring',
            name='cuid',
        ),
        migrations.RemoveField(
            model_name='xdtemporal',
            name='adapter_cuid',
        ),
        migrations.RemoveField(
            model_name='xdtemporal',
            name='cuid',
        ),
        migrations.AlterField(
            model_name='attestation',
            name='ct_id',
            field=models.CharField(default='cjf7edews00001yl3mpzvizpc', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='ct_id',
            field=models.CharField(default='cjf7edews00001yl3mpzvizpc', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='ct_id',
            field=models.CharField(default='cjf7edews00001yl3mpzvizpc', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='dm',
            name='ct_id',
            field=models.CharField(default='cjf7edey200021yl3gibm555l', editable=False, help_text='The unique identifier for the DM.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='ct_id',
            field=models.CharField(default='cjf7edews00001yl3mpzvizpc', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='party',
            name='ct_id',
            field=models.CharField(default='cjf7edews00001yl3mpzvizpc', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='referencerange',
            name='adapter_ctid',
            field=models.CharField(default='cjf7edewu00011yl37xt4fzcl', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='referencerange',
            name='ct_id',
            field=models.CharField(default='cjf7edews00001yl3mpzvizpc', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='simplereferencerange',
            name='adapter_ctid',
            field=models.CharField(default='cjf7edewu00011yl37xt4fzcl', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='simplereferencerange',
            name='ct_id',
            field=models.CharField(default='cjf7edews00001yl3mpzvizpc', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='units',
            name='adapter_ctid',
            field=models.CharField(default='cjf7edewu00011yl37xt4fzcl', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='units',
            name='ct_id',
            field=models.CharField(default='cjf7edews00001yl3mpzvizpc', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdboolean',
            name='adapter_ctid',
            field=models.CharField(default='cjf7edewu00011yl37xt4fzcl', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdboolean',
            name='ct_id',
            field=models.CharField(default='cjf7edews00001yl3mpzvizpc', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdcount',
            name='adapter_ctid',
            field=models.CharField(default='cjf7edewu00011yl37xt4fzcl', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdcount',
            name='ct_id',
            field=models.CharField(default='cjf7edews00001yl3mpzvizpc', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdfile',
            name='adapter_ctid',
            field=models.CharField(default='cjf7edewu00011yl37xt4fzcl', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdfile',
            name='ct_id',
            field=models.CharField(default='cjf7edews00001yl3mpzvizpc', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdfloat',
            name='adapter_ctid',
            field=models.CharField(default='cjf7edewu00011yl37xt4fzcl', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdfloat',
            name='ct_id',
            field=models.CharField(default='cjf7edews00001yl3mpzvizpc', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdinterval',
            name='adapter_ctid',
            field=models.CharField(default='cjf7edewu00011yl37xt4fzcl', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdinterval',
            name='ct_id',
            field=models.CharField(default='cjf7edews00001yl3mpzvizpc', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdlink',
            name='adapter_ctid',
            field=models.CharField(default='cjf7edewu00011yl37xt4fzcl', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdlink',
            name='ct_id',
            field=models.CharField(default='cjf7edews00001yl3mpzvizpc', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdordinal',
            name='adapter_ctid',
            field=models.CharField(default='cjf7edewu00011yl37xt4fzcl', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdordinal',
            name='ct_id',
            field=models.CharField(default='cjf7edews00001yl3mpzvizpc', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdquantity',
            name='adapter_ctid',
            field=models.CharField(default='cjf7edewu00011yl37xt4fzcl', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdquantity',
            name='ct_id',
            field=models.CharField(default='cjf7edews00001yl3mpzvizpc', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdratio',
            name='adapter_ctid',
            field=models.CharField(default='cjf7edewu00011yl37xt4fzcl', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdratio',
            name='ct_id',
            field=models.CharField(default='cjf7edews00001yl3mpzvizpc', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdstring',
            name='adapter_ctid',
            field=models.CharField(default='cjf7edewu00011yl37xt4fzcl', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdstring',
            name='ct_id',
            field=models.CharField(default='cjf7edews00001yl3mpzvizpc', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdtemporal',
            name='adapter_ctid',
            field=models.CharField(default='cjf7edewu00011yl37xt4fzcl', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdtemporal',
            name='ct_id',
            field=models.CharField(default='cjf7edews00001yl3mpzvizpc', editable=False, help_text='The unique identifier for the MC.', max_length=40, verbose_name='CUID'),
        ),
    ]
