# Generated by Django 4.1.7 on 2023-02-25 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tools.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prj_name', models.CharField(db_index=True, help_text='Enter the name of your project.', max_length=110, unique=True, verbose_name='project name')),
                ('description', models.TextField(blank=True, help_text='Enter a description or explaination of an acronym of the project.', verbose_name='project description')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['prj_name'],
            },
        ),
        migrations.CreateModel(
            name='Modeler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the author name as it should appear in DM metadata.', max_length=110, verbose_name='Name')),
                ('email', models.EmailField(help_text='Enter the email address as it should appear in DM metadata as an author and/or contributor.', max_length=110, verbose_name='Email')),
                ('prj_filter', models.BooleanField(default=True, help_text='Uncheck this box if want to see choices from all projects. Note that this will very likely have a negative impact on performance.', verbose_name='Filter by Project')),
                ('project', models.ForeignKey(blank=True, help_text='Choose your default Project.', null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.project', to_field='prj_name', verbose_name='Default Project')),
                ('user', models.ForeignKey(on_delete=models.SET(tools.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modeler',
                'verbose_name_plural': 'Modelers',
                'ordering': ['name', 'email'],
            },
        ),
    ]
