# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmgen', '0004_auto_20170617_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attestation',
            name='asserts',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='asserts',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='asserts',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='asserts',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='asserts',
        ),
        migrations.RemoveField(
            model_name='party',
            name='asserts',
        ),
        migrations.RemoveField(
            model_name='referencerange',
            name='asserts',
        ),
        migrations.RemoveField(
            model_name='simplereferencerange',
            name='asserts',
        ),
        migrations.RemoveField(
            model_name='units',
            name='asserts',
        ),
        migrations.RemoveField(
            model_name='xdboolean',
            name='asserts',
        ),
        migrations.RemoveField(
            model_name='xdcount',
            name='asserts',
        ),
        migrations.RemoveField(
            model_name='xdfile',
            name='asserts',
        ),
        migrations.RemoveField(
            model_name='xdinterval',
            name='asserts',
        ),
        migrations.RemoveField(
            model_name='xdlink',
            name='asserts',
        ),
        migrations.RemoveField(
            model_name='xdordinal',
            name='asserts',
        ),
        migrations.RemoveField(
            model_name='xdquantity',
            name='asserts',
        ),
        migrations.RemoveField(
            model_name='xdratio',
            name='asserts',
        ),
        migrations.RemoveField(
            model_name='xdstring',
            name='asserts',
        ),
        migrations.RemoveField(
            model_name='xdtemporal',
            name='asserts',
        ),
    ]
