# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-14 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmgen', '0006_auto_20170617_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestation',
            name='pred_obj',
            field=models.ManyToManyField(blank=True, help_text='Select or create a new set of RDF Objects as semantic links to define this item.', to='dmgen.PredObj', verbose_name='RDF Object'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='pred_obj',
            field=models.ManyToManyField(blank=True, help_text='Select or create a new set of RDF Objects as semantic links to define this item.', to='dmgen.PredObj', verbose_name='RDF Object'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='pred_obj',
            field=models.ManyToManyField(blank=True, help_text='Select or create a new set of RDF Objects as semantic links to define this item.', to='dmgen.PredObj', verbose_name='RDF Object'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pred_obj',
            field=models.ManyToManyField(blank=True, help_text='Select or create a new set of RDF Objects as semantic links to define this item.', to='dmgen.PredObj', verbose_name='RDF Object'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='pred_obj',
            field=models.ManyToManyField(blank=True, help_text='Select or create a new set of RDF Objects as semantic links to define this item.', to='dmgen.PredObj', verbose_name='RDF Object'),
        ),
        migrations.AlterField(
            model_name='party',
            name='pred_obj',
            field=models.ManyToManyField(blank=True, help_text='Select or create a new set of RDF Objects as semantic links to define this item.', to='dmgen.PredObj', verbose_name='RDF Object'),
        ),
        migrations.AlterField(
            model_name='referencerange',
            name='pred_obj',
            field=models.ManyToManyField(blank=True, help_text='Select or create a new set of RDF Objects as semantic links to define this item.', to='dmgen.PredObj', verbose_name='RDF Object'),
        ),
        migrations.AlterField(
            model_name='simplereferencerange',
            name='pred_obj',
            field=models.ManyToManyField(blank=True, help_text='Select or create a new set of RDF Objects as semantic links to define this item.', to='dmgen.PredObj', verbose_name='RDF Object'),
        ),
        migrations.AlterField(
            model_name='units',
            name='pred_obj',
            field=models.ManyToManyField(blank=True, help_text='Select or create a new set of RDF Objects as semantic links to define this item.', to='dmgen.PredObj', verbose_name='RDF Object'),
        ),
        migrations.AlterField(
            model_name='xdboolean',
            name='pred_obj',
            field=models.ManyToManyField(blank=True, help_text='Select or create a new set of RDF Objects as semantic links to define this item.', to='dmgen.PredObj', verbose_name='RDF Object'),
        ),
        migrations.AlterField(
            model_name='xdcount',
            name='pred_obj',
            field=models.ManyToManyField(blank=True, help_text='Select or create a new set of RDF Objects as semantic links to define this item.', to='dmgen.PredObj', verbose_name='RDF Object'),
        ),
        migrations.AlterField(
            model_name='xdfile',
            name='pred_obj',
            field=models.ManyToManyField(blank=True, help_text='Select or create a new set of RDF Objects as semantic links to define this item.', to='dmgen.PredObj', verbose_name='RDF Object'),
        ),
        migrations.AlterField(
            model_name='xdinterval',
            name='pred_obj',
            field=models.ManyToManyField(blank=True, help_text='Select or create a new set of RDF Objects as semantic links to define this item.', to='dmgen.PredObj', verbose_name='RDF Object'),
        ),
        migrations.AlterField(
            model_name='xdlink',
            name='pred_obj',
            field=models.ManyToManyField(blank=True, help_text='Select or create a new set of RDF Objects as semantic links to define this item.', to='dmgen.PredObj', verbose_name='RDF Object'),
        ),
        migrations.AlterField(
            model_name='xdordinal',
            name='pred_obj',
            field=models.ManyToManyField(blank=True, help_text='Select or create a new set of RDF Objects as semantic links to define this item.', to='dmgen.PredObj', verbose_name='RDF Object'),
        ),
        migrations.AlterField(
            model_name='xdquantity',
            name='pred_obj',
            field=models.ManyToManyField(blank=True, help_text='Select or create a new set of RDF Objects as semantic links to define this item.', to='dmgen.PredObj', verbose_name='RDF Object'),
        ),
        migrations.AlterField(
            model_name='xdratio',
            name='pred_obj',
            field=models.ManyToManyField(blank=True, help_text='Select or create a new set of RDF Objects as semantic links to define this item.', to='dmgen.PredObj', verbose_name='RDF Object'),
        ),
        migrations.AlterField(
            model_name='xdstring',
            name='pred_obj',
            field=models.ManyToManyField(blank=True, help_text='Select or create a new set of RDF Objects as semantic links to define this item.', to='dmgen.PredObj', verbose_name='RDF Object'),
        ),
        migrations.AlterField(
            model_name='xdtemporal',
            name='pred_obj',
            field=models.ManyToManyField(blank=True, help_text='Select or create a new set of RDF Objects as semantic links to define this item.', to='dmgen.PredObj', verbose_name='RDF Object'),
        ),
    ]
