# Generated by Django 2.0.3 on 2018-04-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmgen', '0021_auto_20180414_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='attestation',
            name='public',
            field=models.BooleanField(default=True, help_text='Public components are available to every other modeller. If not public then the component is only visible within the project it was defined in.', verbose_name='Is Public?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='public',
            field=models.BooleanField(default=True, help_text='Public components are available to every other modeller. If not public then the component is only visible within the project it was defined in.', verbose_name='Is Public?'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='public',
            field=models.BooleanField(default=True, help_text='Public components are available to every other modeller. If not public then the component is only visible within the project it was defined in.', verbose_name='Is Public?'),
        ),
        migrations.AddField(
            model_name='participation',
            name='public',
            field=models.BooleanField(default=True, help_text='Public components are available to every other modeller. If not public then the component is only visible within the project it was defined in.', verbose_name='Is Public?'),
        ),
        migrations.AddField(
            model_name='party',
            name='public',
            field=models.BooleanField(default=True, help_text='Public components are available to every other modeller. If not public then the component is only visible within the project it was defined in.', verbose_name='Is Public?'),
        ),
        migrations.AddField(
            model_name='referencerange',
            name='public',
            field=models.BooleanField(default=True, help_text='Public components are available to every other modeller. If not public then the component is only visible within the project it was defined in.', verbose_name='Is Public?'),
        ),
        migrations.AddField(
            model_name='simplereferencerange',
            name='public',
            field=models.BooleanField(default=True, help_text='Public components are available to every other modeller. If not public then the component is only visible within the project it was defined in.', verbose_name='Is Public?'),
        ),
        migrations.AddField(
            model_name='units',
            name='public',
            field=models.BooleanField(default=True, help_text='Public components are available to every other modeller. If not public then the component is only visible within the project it was defined in.', verbose_name='Is Public?'),
        ),
        migrations.AddField(
            model_name='xdboolean',
            name='public',
            field=models.BooleanField(default=True, help_text='Public components are available to every other modeller. If not public then the component is only visible within the project it was defined in.', verbose_name='Is Public?'),
        ),
        migrations.AddField(
            model_name='xdcount',
            name='public',
            field=models.BooleanField(default=True, help_text='Public components are available to every other modeller. If not public then the component is only visible within the project it was defined in.', verbose_name='Is Public?'),
        ),
        migrations.AddField(
            model_name='xdfile',
            name='public',
            field=models.BooleanField(default=True, help_text='Public components are available to every other modeller. If not public then the component is only visible within the project it was defined in.', verbose_name='Is Public?'),
        ),
        migrations.AddField(
            model_name='xdfloat',
            name='public',
            field=models.BooleanField(default=True, help_text='Public components are available to every other modeller. If not public then the component is only visible within the project it was defined in.', verbose_name='Is Public?'),
        ),
        migrations.AddField(
            model_name='xdinterval',
            name='public',
            field=models.BooleanField(default=True, help_text='Public components are available to every other modeller. If not public then the component is only visible within the project it was defined in.', verbose_name='Is Public?'),
        ),
        migrations.AddField(
            model_name='xdlink',
            name='public',
            field=models.BooleanField(default=True, help_text='Public components are available to every other modeller. If not public then the component is only visible within the project it was defined in.', verbose_name='Is Public?'),
        ),
        migrations.AddField(
            model_name='xdordinal',
            name='public',
            field=models.BooleanField(default=True, help_text='Public components are available to every other modeller. If not public then the component is only visible within the project it was defined in.', verbose_name='Is Public?'),
        ),
        migrations.AddField(
            model_name='xdquantity',
            name='public',
            field=models.BooleanField(default=True, help_text='Public components are available to every other modeller. If not public then the component is only visible within the project it was defined in.', verbose_name='Is Public?'),
        ),
        migrations.AddField(
            model_name='xdratio',
            name='public',
            field=models.BooleanField(default=True, help_text='Public components are available to every other modeller. If not public then the component is only visible within the project it was defined in.', verbose_name='Is Public?'),
        ),
        migrations.AddField(
            model_name='xdstring',
            name='public',
            field=models.BooleanField(default=True, help_text='Public components are available to every other modeller. If not public then the component is only visible within the project it was defined in.', verbose_name='Is Public?'),
        ),
        migrations.AddField(
            model_name='xdtemporal',
            name='public',
            field=models.BooleanField(default=True, help_text='Public components are available to every other modeller. If not public then the component is only visible within the project it was defined in.', verbose_name='Is Public?'),
        ),
        migrations.AlterField(
            model_name='attestation',
            name='ct_id',
            field=models.CharField(default='cjgaogt9d0000b2l37kv1h73d', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='ct_id',
            field=models.CharField(default='cjgaogt9d0000b2l37kv1h73d', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='ct_id',
            field=models.CharField(default='cjgaogt9d0000b2l37kv1h73d', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='dm',
            name='ct_id',
            field=models.CharField(default='cjgaogtaq0002b2l3kunstick', editable=False, help_text='The unique identifier for the DM.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='ct_id',
            field=models.CharField(default='cjgaogt9d0000b2l37kv1h73d', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='party',
            name='ct_id',
            field=models.CharField(default='cjgaogt9d0000b2l37kv1h73d', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='referencerange',
            name='adapter_ctid',
            field=models.CharField(default='cjgaogt9f0001b2l3soa8qd90', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='referencerange',
            name='ct_id',
            field=models.CharField(default='cjgaogt9d0000b2l37kv1h73d', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='simplereferencerange',
            name='adapter_ctid',
            field=models.CharField(default='cjgaogt9f0001b2l3soa8qd90', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='simplereferencerange',
            name='ct_id',
            field=models.CharField(default='cjgaogt9d0000b2l37kv1h73d', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='units',
            name='adapter_ctid',
            field=models.CharField(default='cjgaogt9f0001b2l3soa8qd90', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='units',
            name='ct_id',
            field=models.CharField(default='cjgaogt9d0000b2l37kv1h73d', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdboolean',
            name='adapter_ctid',
            field=models.CharField(default='cjgaogt9f0001b2l3soa8qd90', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdboolean',
            name='ct_id',
            field=models.CharField(default='cjgaogt9d0000b2l37kv1h73d', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdcount',
            name='adapter_ctid',
            field=models.CharField(default='cjgaogt9f0001b2l3soa8qd90', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdcount',
            name='ct_id',
            field=models.CharField(default='cjgaogt9d0000b2l37kv1h73d', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdfile',
            name='adapter_ctid',
            field=models.CharField(default='cjgaogt9f0001b2l3soa8qd90', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdfile',
            name='content_mode',
            field=models.CharField(choices=[('select', 'Select Mode:'), ('url', 'Link via a URL'), ('embed', 'Embed a file')], default='Select Mode:', help_text='Select how the content will referenced, either via a URL or included in the data instance.', max_length=6, verbose_name='Content Mode'),
        ),
        migrations.AlterField(
            model_name='xdfile',
            name='ct_id',
            field=models.CharField(default='cjgaogt9d0000b2l37kv1h73d', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdfloat',
            name='adapter_ctid',
            field=models.CharField(default='cjgaogt9f0001b2l3soa8qd90', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdfloat',
            name='ct_id',
            field=models.CharField(default='cjgaogt9d0000b2l37kv1h73d', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdinterval',
            name='adapter_ctid',
            field=models.CharField(default='cjgaogt9f0001b2l3soa8qd90', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdinterval',
            name='ct_id',
            field=models.CharField(default='cjgaogt9d0000b2l37kv1h73d', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdlink',
            name='adapter_ctid',
            field=models.CharField(default='cjgaogt9f0001b2l3soa8qd90', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdlink',
            name='ct_id',
            field=models.CharField(default='cjgaogt9d0000b2l37kv1h73d', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdordinal',
            name='adapter_ctid',
            field=models.CharField(default='cjgaogt9f0001b2l3soa8qd90', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdordinal',
            name='ct_id',
            field=models.CharField(default='cjgaogt9d0000b2l37kv1h73d', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdquantity',
            name='adapter_ctid',
            field=models.CharField(default='cjgaogt9f0001b2l3soa8qd90', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdquantity',
            name='ct_id',
            field=models.CharField(default='cjgaogt9d0000b2l37kv1h73d', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdratio',
            name='adapter_ctid',
            field=models.CharField(default='cjgaogt9f0001b2l3soa8qd90', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdratio',
            name='ct_id',
            field=models.CharField(default='cjgaogt9d0000b2l37kv1h73d', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdstring',
            name='adapter_ctid',
            field=models.CharField(default='cjgaogt9f0001b2l3soa8qd90', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdstring',
            name='ct_id',
            field=models.CharField(default='cjgaogt9d0000b2l37kv1h73d', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdtemporal',
            name='adapter_ctid',
            field=models.CharField(default='cjgaogt9f0001b2l3soa8qd90', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdtemporal',
            name='ct_id',
            field=models.CharField(default='cjgaogt9d0000b2l37kv1h73d', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
    ]
