# Generated by Django 2.0.3 on 2018-04-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmgen', '0023_auto_20180422_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='attestation',
            name='validate',
            field=models.BooleanField(default=False, help_text='Hard validation is when the UI enforces criteria on input fields. Soft validation allows users to input any value, warns them when it is not within parameters of the DM. Then offers to allow correction or select an Exceptional Value as explaination.', verbose_name='Hard Validate?'),
        ),
        migrations.AddField(
            model_name='audit',
            name='validate',
            field=models.BooleanField(default=False, help_text='Hard validation is when the UI enforces criteria on input fields. Soft validation allows users to input any value, warns them when it is not within parameters of the DM. Then offers to allow correction or select an Exceptional Value as explaination.', verbose_name='Hard Validate?'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='validate',
            field=models.BooleanField(default=False, help_text='Hard validation is when the UI enforces criteria on input fields. Soft validation allows users to input any value, warns them when it is not within parameters of the DM. Then offers to allow correction or select an Exceptional Value as explaination.', verbose_name='Hard Validate?'),
        ),
        migrations.AddField(
            model_name='participation',
            name='validate',
            field=models.BooleanField(default=False, help_text='Hard validation is when the UI enforces criteria on input fields. Soft validation allows users to input any value, warns them when it is not within parameters of the DM. Then offers to allow correction or select an Exceptional Value as explaination.', verbose_name='Hard Validate?'),
        ),
        migrations.AddField(
            model_name='party',
            name='validate',
            field=models.BooleanField(default=False, help_text='Hard validation is when the UI enforces criteria on input fields. Soft validation allows users to input any value, warns them when it is not within parameters of the DM. Then offers to allow correction or select an Exceptional Value as explaination.', verbose_name='Hard Validate?'),
        ),
        migrations.AddField(
            model_name='referencerange',
            name='validate',
            field=models.BooleanField(default=False, help_text='Hard validation is when the UI enforces criteria on input fields. Soft validation allows users to input any value, warns them when it is not within parameters of the DM. Then offers to allow correction or select an Exceptional Value as explaination.', verbose_name='Hard Validate?'),
        ),
        migrations.AddField(
            model_name='simplereferencerange',
            name='validate',
            field=models.BooleanField(default=False, help_text='Hard validation is when the UI enforces criteria on input fields. Soft validation allows users to input any value, warns them when it is not within parameters of the DM. Then offers to allow correction or select an Exceptional Value as explaination.', verbose_name='Hard Validate?'),
        ),
        migrations.AddField(
            model_name='units',
            name='validate',
            field=models.BooleanField(default=False, help_text='Hard validation is when the UI enforces criteria on input fields. Soft validation allows users to input any value, warns them when it is not within parameters of the DM. Then offers to allow correction or select an Exceptional Value as explaination.', verbose_name='Hard Validate?'),
        ),
        migrations.AddField(
            model_name='xdboolean',
            name='validate',
            field=models.BooleanField(default=False, help_text='Hard validation is when the UI enforces criteria on input fields. Soft validation allows users to input any value, warns them when it is not within parameters of the DM. Then offers to allow correction or select an Exceptional Value as explaination.', verbose_name='Hard Validate?'),
        ),
        migrations.AddField(
            model_name='xdcount',
            name='validate',
            field=models.BooleanField(default=False, help_text='Hard validation is when the UI enforces criteria on input fields. Soft validation allows users to input any value, warns them when it is not within parameters of the DM. Then offers to allow correction or select an Exceptional Value as explaination.', verbose_name='Hard Validate?'),
        ),
        migrations.AddField(
            model_name='xdfile',
            name='validate',
            field=models.BooleanField(default=False, help_text='Hard validation is when the UI enforces criteria on input fields. Soft validation allows users to input any value, warns them when it is not within parameters of the DM. Then offers to allow correction or select an Exceptional Value as explaination.', verbose_name='Hard Validate?'),
        ),
        migrations.AddField(
            model_name='xdfloat',
            name='validate',
            field=models.BooleanField(default=False, help_text='Hard validation is when the UI enforces criteria on input fields. Soft validation allows users to input any value, warns them when it is not within parameters of the DM. Then offers to allow correction or select an Exceptional Value as explaination.', verbose_name='Hard Validate?'),
        ),
        migrations.AddField(
            model_name='xdinterval',
            name='validate',
            field=models.BooleanField(default=False, help_text='Hard validation is when the UI enforces criteria on input fields. Soft validation allows users to input any value, warns them when it is not within parameters of the DM. Then offers to allow correction or select an Exceptional Value as explaination.', verbose_name='Hard Validate?'),
        ),
        migrations.AddField(
            model_name='xdlink',
            name='validate',
            field=models.BooleanField(default=False, help_text='Hard validation is when the UI enforces criteria on input fields. Soft validation allows users to input any value, warns them when it is not within parameters of the DM. Then offers to allow correction or select an Exceptional Value as explaination.', verbose_name='Hard Validate?'),
        ),
        migrations.AddField(
            model_name='xdordinal',
            name='validate',
            field=models.BooleanField(default=False, help_text='Hard validation is when the UI enforces criteria on input fields. Soft validation allows users to input any value, warns them when it is not within parameters of the DM. Then offers to allow correction or select an Exceptional Value as explaination.', verbose_name='Hard Validate?'),
        ),
        migrations.AddField(
            model_name='xdquantity',
            name='validate',
            field=models.BooleanField(default=False, help_text='Hard validation is when the UI enforces criteria on input fields. Soft validation allows users to input any value, warns them when it is not within parameters of the DM. Then offers to allow correction or select an Exceptional Value as explaination.', verbose_name='Hard Validate?'),
        ),
        migrations.AddField(
            model_name='xdratio',
            name='validate',
            field=models.BooleanField(default=False, help_text='Hard validation is when the UI enforces criteria on input fields. Soft validation allows users to input any value, warns them when it is not within parameters of the DM. Then offers to allow correction or select an Exceptional Value as explaination.', verbose_name='Hard Validate?'),
        ),
        migrations.AddField(
            model_name='xdstring',
            name='validate',
            field=models.BooleanField(default=False, help_text='Hard validation is when the UI enforces criteria on input fields. Soft validation allows users to input any value, warns them when it is not within parameters of the DM. Then offers to allow correction or select an Exceptional Value as explaination.', verbose_name='Hard Validate?'),
        ),
        migrations.AddField(
            model_name='xdtemporal',
            name='validate',
            field=models.BooleanField(default=False, help_text='Hard validation is when the UI enforces criteria on input fields. Soft validation allows users to input any value, warns them when it is not within parameters of the DM. Then offers to allow correction or select an Exceptional Value as explaination.', verbose_name='Hard Validate?'),
        ),
        migrations.AlterField(
            model_name='attestation',
            name='ct_id',
            field=models.CharField(default='cjgaqxfu00000h1l3xdxmsryt', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='ct_id',
            field=models.CharField(default='cjgaqxfu00000h1l3xdxmsryt', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='ct_id',
            field=models.CharField(default='cjgaqxfu00000h1l3xdxmsryt', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='dm',
            name='ct_id',
            field=models.CharField(default='cjgaqxfvh0002h1l3aozs01tt', editable=False, help_text='The unique identifier for the DM.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='ct_id',
            field=models.CharField(default='cjgaqxfu00000h1l3xdxmsryt', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='party',
            name='ct_id',
            field=models.CharField(default='cjgaqxfu00000h1l3xdxmsryt', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='referencerange',
            name='adapter_ctid',
            field=models.CharField(default='cjgaqxfu10001h1l3p6brqux0', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='referencerange',
            name='ct_id',
            field=models.CharField(default='cjgaqxfu00000h1l3xdxmsryt', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='simplereferencerange',
            name='adapter_ctid',
            field=models.CharField(default='cjgaqxfu10001h1l3p6brqux0', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='simplereferencerange',
            name='ct_id',
            field=models.CharField(default='cjgaqxfu00000h1l3xdxmsryt', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='units',
            name='adapter_ctid',
            field=models.CharField(default='cjgaqxfu10001h1l3p6brqux0', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='units',
            name='ct_id',
            field=models.CharField(default='cjgaqxfu00000h1l3xdxmsryt', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdboolean',
            name='adapter_ctid',
            field=models.CharField(default='cjgaqxfu10001h1l3p6brqux0', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdboolean',
            name='ct_id',
            field=models.CharField(default='cjgaqxfu00000h1l3xdxmsryt', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdcount',
            name='adapter_ctid',
            field=models.CharField(default='cjgaqxfu10001h1l3p6brqux0', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdcount',
            name='ct_id',
            field=models.CharField(default='cjgaqxfu00000h1l3xdxmsryt', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdfile',
            name='adapter_ctid',
            field=models.CharField(default='cjgaqxfu10001h1l3p6brqux0', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdfile',
            name='ct_id',
            field=models.CharField(default='cjgaqxfu00000h1l3xdxmsryt', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdfloat',
            name='adapter_ctid',
            field=models.CharField(default='cjgaqxfu10001h1l3p6brqux0', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdfloat',
            name='ct_id',
            field=models.CharField(default='cjgaqxfu00000h1l3xdxmsryt', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdinterval',
            name='adapter_ctid',
            field=models.CharField(default='cjgaqxfu10001h1l3p6brqux0', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdinterval',
            name='ct_id',
            field=models.CharField(default='cjgaqxfu00000h1l3xdxmsryt', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdlink',
            name='adapter_ctid',
            field=models.CharField(default='cjgaqxfu10001h1l3p6brqux0', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdlink',
            name='ct_id',
            field=models.CharField(default='cjgaqxfu00000h1l3xdxmsryt', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdordinal',
            name='adapter_ctid',
            field=models.CharField(default='cjgaqxfu10001h1l3p6brqux0', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdordinal',
            name='ct_id',
            field=models.CharField(default='cjgaqxfu00000h1l3xdxmsryt', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdquantity',
            name='adapter_ctid',
            field=models.CharField(default='cjgaqxfu10001h1l3p6brqux0', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdquantity',
            name='ct_id',
            field=models.CharField(default='cjgaqxfu00000h1l3xdxmsryt', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdratio',
            name='adapter_ctid',
            field=models.CharField(default='cjgaqxfu10001h1l3p6brqux0', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdratio',
            name='ct_id',
            field=models.CharField(default='cjgaqxfu00000h1l3xdxmsryt', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdstring',
            name='adapter_ctid',
            field=models.CharField(default='cjgaqxfu10001h1l3p6brqux0', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdstring',
            name='ct_id',
            field=models.CharField(default='cjgaqxfu00000h1l3xdxmsryt', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdtemporal',
            name='adapter_ctid',
            field=models.CharField(default='cjgaqxfu10001h1l3p6brqux0', editable=False, help_text='This UUID is generated for datatype that can be included in a Cluster. It is used to create a specific XdAdapter complexType.', max_length=40, unique=True, verbose_name='CUID'),
        ),
        migrations.AlterField(
            model_name='xdtemporal',
            name='ct_id',
            field=models.CharField(default='cjgaqxfu00000h1l3xdxmsryt', editable=False, help_text='The unique identifier for the MC.', max_length=40, unique=True, verbose_name='CUID'),
        ),
    ]
